# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.api.prices_api import PricesApi


class TestPricesApi(unittest.TestCase):
    """PricesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PricesApi()

    def tearDown(self) -> None:
        pass

    def test_batch_price_lookup(self) -> None:
        """Test case for batch_price_lookup

        Batch Price Lookup
        """
        pass

    def test_list_prices(self) -> None:
        """Test case for list_prices

        List Prices
        """
        pass

    def test_price_candles(self) -> None:
        """Test case for price_candles

        Price Candles
        """
        pass

    def test_price_history(self) -> None:
        """Test case for price_history

        Price History
        """
        pass

    def test_stream_full_prices_snapshot(self) -> None:
        """Test case for stream_full_prices_snapshot

        Stream Full Prices Snapshot
        """
        pass


if __name__ == '__main__':
    unittest.main()
