# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.api.market_intelligence_api import MarketIntelligenceApi


class TestMarketIntelligenceApi(unittest.TestCase):
    """MarketIntelligenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketIntelligenceApi()

    def tearDown(self) -> None:
        pass

    def test_get_arbitrage_opportunities_v1_market_arbitrage_get(self) -> None:
        """Test case for get_arbitrage_opportunities_v1_market_arbitrage_get

        Get Arbitrage Opportunities
        """
        pass

    def test_get_indicators_v1_market_indicators_get(self) -> None:
        """Test case for get_indicators_v1_market_indicators_get

        Get Indicators
        """
        pass

    def test_get_item_analytics_v1_market_items_item_id_get(self) -> None:
        """Test case for get_item_analytics_v1_market_items_item_id_get

        Get Item Analytics
        """
        pass


if __name__ == '__main__':
    unittest.main()
