# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.batch_price_quote import BatchPriceQuote

class TestBatchPriceQuote(unittest.TestCase):
    """BatchPriceQuote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchPriceQuote:
        """Test BatchPriceQuote
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchPriceQuote`
        """
        model = BatchPriceQuote()
        if include_optional:
            return BatchPriceQuote(
                provider = '',
                lowest_ask = 56,
                quantity = 56,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BatchPriceQuote(
                provider = '',
                lowest_ask = 56,
                quantity = 56,
        )
        """

    def testBatchPriceQuote(self):
        """Test BatchPriceQuote"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
