# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.models.market_indexes_response import MarketIndexesResponse

class TestMarketIndexesResponse(unittest.TestCase):
    """MarketIndexesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketIndexesResponse:
        """Test MarketIndexesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketIndexesResponse`
        """
        model = MarketIndexesResponse()
        if include_optional:
            return MarketIndexesResponse(
                meta = cs2cap.models.market_indexes_meta.MarketIndexesMeta(
                    generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    data_source = 'cache', 
                    freshness_sec = 0.0, 
                    window = null, 
                    group_by = 'item_type', ),
                data = ERROR_TO_EXAMPLE_VALUE
            )
        else:
            return MarketIndexesResponse(
                meta = cs2cap.models.market_indexes_meta.MarketIndexesMeta(
                    generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    data_source = 'cache', 
                    freshness_sec = 0.0, 
                    window = null, 
                    group_by = 'item_type', ),
                data = ERROR_TO_EXAMPLE_VALUE,
        )
        """

    def testMarketIndexesResponse(self):
        """Test MarketIndexesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
