# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.ip_reset_response import IPResetResponse

class TestIPResetResponse(unittest.TestCase):
    """IPResetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IPResetResponse:
        """Test IPResetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IPResetResponse`
        """
        model = IPResetResponse()
        if include_optional:
            return IPResetResponse(
                ok = True,
                key_id = '',
                cooldown_sec = 56
            )
        else:
            return IPResetResponse(
                ok = True,
                key_id = '',
                cooldown_sec = 56,
        )
        """

    def testIPResetResponse(self):
        """Test IPResetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
