# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.price_snapshot import PriceSnapshot

class TestPriceSnapshot(unittest.TestCase):
    """PriceSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PriceSnapshot:
        """Test PriceSnapshot
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PriceSnapshot`
        """
        model = PriceSnapshot()
        if include_optional:
            return PriceSnapshot(
                item_id = 56,
                market_hash_name = '',
                phase = '',
                provider = '',
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                price = 56,
                currency = '',
                quantity = 56
            )
        else:
            return PriceSnapshot(
                item_id = 56,
                market_hash_name = '',
                provider = '',
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                price = 56,
                currency = '',
                quantity = 56,
        )
        """

    def testPriceSnapshot(self):
        """Test PriceSnapshot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
