# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.market_items_snapshot_data import MarketItemsSnapshotData

class TestMarketItemsSnapshotData(unittest.TestCase):
    """MarketItemsSnapshotData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketItemsSnapshotData:
        """Test MarketItemsSnapshotData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketItemsSnapshotData`
        """
        model = MarketItemsSnapshotData()
        if include_optional:
            return MarketItemsSnapshotData(
                items = [
                    cs2cap_sdk.models.market_items_snapshot_item.MarketItemsSnapshotItem(
                        item_id = 56, 
                        market_hash_name = '', 
                        phase = '', 
                        summary = null, )
                    ]
            )
        else:
            return MarketItemsSnapshotData(
                items = [
                    cs2cap_sdk.models.market_items_snapshot_item.MarketItemsSnapshotItem(
                        item_id = 56, 
                        market_hash_name = '', 
                        phase = '', 
                        summary = null, )
                    ],
        )
        """

    def testMarketItemsSnapshotData(self):
        """Test MarketItemsSnapshotData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
