# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.portfolio_response import PortfolioResponse

class TestPortfolioResponse(unittest.TestCase):
    """PortfolioResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PortfolioResponse:
        """Test PortfolioResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PortfolioResponse`
        """
        model = PortfolioResponse()
        if include_optional:
            return PortfolioResponse(
                meta = cs2cap_sdk.models.portfolio_meta.PortfolioMeta(
                    currency = '', 
                    generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    providers_queried = [
                        ''
                        ], ),
                data = cs2cap_sdk.models.portfolio_data.PortfolioData(
                    line_items = [
                        cs2cap_sdk.models.portfolio_line_item.PortfolioLineItem(
                            item_id = 56, 
                            market_hash_name = '', 
                            phase = '', 
                            quantity = 56, 
                            best_ask = 56, 
                            best_bid = 56, 
                            item_value = 56, 
                            providers = [
                                cs2cap_sdk.models.batch_price_quote.BatchPriceQuote(
                                    provider = '', 
                                    lowest_ask = 56, 
                                    quantity = 56, 
                                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], )
                        ], 
                    total_value = 56, 
                    items_valued = 56, 
                    items_not_found = [
                        56
                        ], )
            )
        else:
            return PortfolioResponse(
                meta = cs2cap_sdk.models.portfolio_meta.PortfolioMeta(
                    currency = '', 
                    generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    providers_queried = [
                        ''
                        ], ),
                data = cs2cap_sdk.models.portfolio_data.PortfolioData(
                    line_items = [
                        cs2cap_sdk.models.portfolio_line_item.PortfolioLineItem(
                            item_id = 56, 
                            market_hash_name = '', 
                            phase = '', 
                            quantity = 56, 
                            best_ask = 56, 
                            best_bid = 56, 
                            item_value = 56, 
                            providers = [
                                cs2cap_sdk.models.batch_price_quote.BatchPriceQuote(
                                    provider = '', 
                                    lowest_ask = 56, 
                                    quantity = 56, 
                                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], )
                        ], 
                    total_value = 56, 
                    items_valued = 56, 
                    items_not_found = [
                        56
                        ], ),
        )
        """

    def testPortfolioResponse(self):
        """Test PortfolioResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
