# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.api.bids_api import BidsApi


class TestBidsApi(unittest.TestCase):
    """BidsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BidsApi()

    def tearDown(self) -> None:
        pass

    def test_batch_bid_lookup(self) -> None:
        """Test case for batch_bid_lookup

        Batch Bid Lookup
        """
        pass

    def test_list_bids(self) -> None:
        """Test case for list_bids

        List Bids
        """
        pass

    def test_stream_full_bids_snapshot(self) -> None:
        """Test case for stream_full_bids_snapshot

        Stream Full Bids Snapshot
        """
        pass


if __name__ == '__main__':
    unittest.main()
