# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.models.webhook_create_request import WebhookCreateRequest

class TestWebhookCreateRequest(unittest.TestCase):
    """WebhookCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookCreateRequest:
        """Test WebhookCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookCreateRequest`
        """
        model = WebhookCreateRequest()
        if include_optional:
            return WebhookCreateRequest(
                label = '',
                url = '',
                is_active = True
            )
        else:
            return WebhookCreateRequest(
                label = '',
                url = '',
        )
        """

    def testWebhookCreateRequest(self):
        """Test WebhookCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
