# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.market_item_analytics_data import MarketItemAnalyticsData

class TestMarketItemAnalyticsData(unittest.TestCase):
    """MarketItemAnalyticsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketItemAnalyticsData:
        """Test MarketItemAnalyticsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketItemAnalyticsData`
        """
        model = MarketItemAnalyticsData()
        if include_optional:
            return MarketItemAnalyticsData(
                item_id = 56,
                market_hash_name = '',
                phase = '',
                summary = ERROR_TO_EXAMPLE_VALUE,
                providers = ERROR_TO_EXAMPLE_VALUE,
                coverage = cs2cap_sdk.models.market_item_analytics_coverage.MarketItemAnalyticsCoverage(
                    provider_count = 56, 
                    providers_with_volume = 56, 
                    providers_with_liquidity = 56, 
                    providers_with_bid_side = 56, )
            )
        else:
            return MarketItemAnalyticsData(
                item_id = 56,
                market_hash_name = '',
                summary = ERROR_TO_EXAMPLE_VALUE,
                providers = ERROR_TO_EXAMPLE_VALUE,
                coverage = cs2cap_sdk.models.market_item_analytics_coverage.MarketItemAnalyticsCoverage(
                    provider_count = 56, 
                    providers_with_volume = 56, 
                    providers_with_liquidity = 56, 
                    providers_with_bid_side = 56, ),
        )
        """

    def testMarketItemAnalyticsData(self):
        """Test MarketItemAnalyticsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
