# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.api.items_api import ItemsApi


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsApi()

    def tearDown(self) -> None:
        pass

    def test_get_item_catalog_metadata(self) -> None:
        """Test case for get_item_catalog_metadata

        Get Item Catalog Metadata
        """
        pass

    def test_list_items(self) -> None:
        """Test case for list_items

        List Items
        """
        pass


if __name__ == '__main__':
    unittest.main()
