# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.item_out import ItemOut

class TestItemOut(unittest.TestCase):
    """ItemOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemOut:
        """Test ItemOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemOut`
        """
        model = ItemOut()
        if include_optional:
            return ItemOut(
                item_id = 56,
                market_hash_name = '',
                phase = '',
                item_type = '',
                item_subtype = '',
                weapon_type = '',
                base_name = '',
                skin_name = '',
                wear_name = '',
                def_index = '',
                paint_index = 56,
                collection = '',
                crates = [
                    ''
                    ],
                rarity_name = '',
                rarity_color = '',
                style_name = '',
                is_stattrak = True,
                is_souvenir = True,
                min_float = 1.337,
                max_float = 1.337,
                image_url = '',
                supply = 56
            )
        else:
            return ItemOut(
                market_hash_name = '',
        )
        """

    def testItemOut(self):
        """Test ItemOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
