# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.api.account_webhooks_api import AccountWebhooksApi


class TestAccountWebhooksApi(unittest.TestCase):
    """AccountWebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountWebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook(self) -> None:
        """Test case for create_webhook

        Create Webhook
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete Webhook
        """
        pass

    def test_get_webhook_delivery(self) -> None:
        """Test case for get_webhook_delivery

        Get Webhook Delivery
        """
        pass

    def test_list_webhook_deliveries(self) -> None:
        """Test case for list_webhook_deliveries

        List Webhook Deliveries
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List Webhooks
        """
        pass

    def test_rotate_webhook_secret(self) -> None:
        """Test case for rotate_webhook_secret

        Rotate Webhook Secret
        """
        pass

    def test_update_webhook(self) -> None:
        """Test case for update_webhook

        Update Webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
