# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.models.batch_bids_response import BatchBidsResponse

class TestBatchBidsResponse(unittest.TestCase):
    """BatchBidsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchBidsResponse:
        """Test BatchBidsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchBidsResponse`
        """
        model = BatchBidsResponse()
        if include_optional:
            return BatchBidsResponse(
                meta = cs2cap.models.batch_bids_meta.BatchBidsMeta(
                    currency = '', 
                    requested_item_count = 56, 
                    found_item_count = 56, 
                    providers_queried = [
                        ''
                        ], 
                    generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                items = [
                    cs2cap.models.batch_bid_item.BatchBidItem(
                        item_id = 56, 
                        market_hash_name = '', 
                        phase = '', 
                        quotes = [
                            cs2cap.models.batch_bid_quote.BatchBidQuote(
                                provider = '', 
                                highest_bid = 56, 
                                num_bids = 56, 
                                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], )
                    ],
                items_not_found = [
                    56
                    ],
                names_not_found = [
                    ''
                    ]
            )
        else:
            return BatchBidsResponse(
                meta = cs2cap.models.batch_bids_meta.BatchBidsMeta(
                    currency = '', 
                    requested_item_count = 56, 
                    found_item_count = 56, 
                    providers_queried = [
                        ''
                        ], 
                    generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                items = [
                    cs2cap.models.batch_bid_item.BatchBidItem(
                        item_id = 56, 
                        market_hash_name = '', 
                        phase = '', 
                        quotes = [
                            cs2cap.models.batch_bid_quote.BatchBidQuote(
                                provider = '', 
                                highest_bid = 56, 
                                num_bids = 56, 
                                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], )
                    ],
                items_not_found = [
                    56
                    ],
        )
        """

    def testBatchBidsResponse(self):
        """Test BatchBidsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
