# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.child_api_key_list_response import ChildAPIKeyListResponse

class TestChildAPIKeyListResponse(unittest.TestCase):
    """ChildAPIKeyListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChildAPIKeyListResponse:
        """Test ChildAPIKeyListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChildAPIKeyListResponse`
        """
        model = ChildAPIKeyListResponse()
        if include_optional:
            return ChildAPIKeyListResponse(
                keys = [
                    cs2cap_sdk.models.child_api_key_detail_response.ChildAPIKeyDetailResponse(
                        key = null, 
                        requests_this_month = 56, )
                    ],
                pagination = cs2cap_sdk.models.pagination_meta.PaginationMeta(
                    limit = 1.0, 
                    offset = 0.0, 
                    total = -1.0, 
                    has_next = True, 
                    has_prev = True, 
                    next_cursor = '', )
            )
        else:
            return ChildAPIKeyListResponse(
                keys = [
                    cs2cap_sdk.models.child_api_key_detail_response.ChildAPIKeyDetailResponse(
                        key = null, 
                        requests_this_month = 56, )
                    ],
                pagination = cs2cap_sdk.models.pagination_meta.PaginationMeta(
                    limit = 1.0, 
                    offset = 0.0, 
                    total = -1.0, 
                    has_next = True, 
                    has_prev = True, 
                    next_cursor = '', ),
        )
        """

    def testChildAPIKeyListResponse(self):
        """Test ChildAPIKeyListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
