# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.models.indicator_volatility import IndicatorVolatility

class TestIndicatorVolatility(unittest.TestCase):
    """IndicatorVolatility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndicatorVolatility:
        """Test IndicatorVolatility
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndicatorVolatility`
        """
        model = IndicatorVolatility()
        if include_optional:
            return IndicatorVolatility(
                atr_14 = 1.337,
                historical_volatility_20 = 1.337,
                kc_upper = 1.337,
                kc_middle = 1.337,
                kc_lower = 1.337
            )
        else:
            return IndicatorVolatility(
        )
        """

    def testIndicatorVolatility(self):
        """Test IndicatorVolatility"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
