# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.models.market_indexes_data import MarketIndexesData

class TestMarketIndexesData(unittest.TestCase):
    """MarketIndexesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketIndexesData:
        """Test MarketIndexesData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketIndexesData`
        """
        model = MarketIndexesData()
        if include_optional:
            return MarketIndexesData(
                total_marketcap_usd = ERROR_TO_EXAMPLE_VALUE,
                groups = ERROR_TO_EXAMPLE_VALUE
            )
        else:
            return MarketIndexesData(
                total_marketcap_usd = ERROR_TO_EXAMPLE_VALUE,
                groups = ERROR_TO_EXAMPLE_VALUE,
        )
        """

    def testMarketIndexesData(self):
        """Test MarketIndexesData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
