# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.steam_inventory_item import SteamInventoryItem

class TestSteamInventoryItem(unittest.TestCase):
    """SteamInventoryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SteamInventoryItem:
        """Test SteamInventoryItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SteamInventoryItem`
        """
        model = SteamInventoryItem()
        if include_optional:
            return SteamInventoryItem(
                assetid = '',
                market_hash_name = '',
                phase = '',
                name = '',
                icon_url = '',
                tradable = True,
                marketable = True,
                quantity = 56,
                float_value = 1.337,
                paint_seed = 56,
                inspect_link = '',
                name_tag = '',
                stickers = [
                    cs2cap_sdk.models.sticker_info.StickerInfo(
                        name = '', 
                        slot = 56, 
                        wear = 1.337, )
                    ],
                charms = [
                    cs2cap_sdk.models.charm_info.CharmInfo(
                        name = '', 
                        pattern_id = 56, )
                    ]
            )
        else:
            return SteamInventoryItem(
                assetid = '',
                market_hash_name = '',
                name = '',
                tradable = True,
                marketable = True,
                quantity = 56,
        )
        """

    def testSteamInventoryItem(self):
        """Test SteamInventoryItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
