# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.market_indices_meta import MarketIndicesMeta

class TestMarketIndicesMeta(unittest.TestCase):
    """MarketIndicesMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketIndicesMeta:
        """Test MarketIndicesMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketIndicesMeta`
        """
        model = MarketIndicesMeta()
        if include_optional:
            return MarketIndicesMeta(
                generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_source = 'cache',
                freshness_sec = 0.0,
                window = cs2cap_sdk.models.market_time_window_meta.MarketTimeWindowMeta(
                    timeframe = '', ),
                group_by = 'item_type'
            )
        else:
            return MarketIndicesMeta(
                generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_source = 'cache',
                freshness_sec = 0.0,
                group_by = 'item_type',
        )
        """

    def testMarketIndicesMeta(self):
        """Test MarketIndicesMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
