# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.market_indicators_item_data import MarketIndicatorsItemData

class TestMarketIndicatorsItemData(unittest.TestCase):
    """MarketIndicatorsItemData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketIndicatorsItemData:
        """Test MarketIndicatorsItemData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketIndicatorsItemData`
        """
        model = MarketIndicatorsItemData()
        if include_optional:
            return MarketIndicatorsItemData(
                item_id = 56,
                market_hash_name = '',
                phase = '',
                provider = '',
                interval = '',
                close_price_usd = ERROR_TO_EXAMPLE_VALUE,
                momentum = cs2cap_sdk.models.indicator_momentum.IndicatorMomentum(
                    rsi_14 = 1.337, 
                    macd_line = 1.337, 
                    macd_signal = 1.337, 
                    macd_histogram = 1.337, 
                    sma_20 = 1.337, 
                    sma_50 = 1.337, 
                    sma_200 = 1.337, 
                    ema_12 = 1.337, 
                    ema_26 = 1.337, 
                    bb_upper = 1.337, 
                    bb_middle = 1.337, 
                    bb_lower = 1.337, ),
                volatility = cs2cap_sdk.models.indicator_volatility.IndicatorVolatility(
                    atr_14 = 1.337, 
                    historical_volatility_20 = 1.337, 
                    kc_upper = 1.337, 
                    kc_middle = 1.337, 
                    kc_lower = 1.337, ),
                volume = cs2cap_sdk.models.indicator_volume.IndicatorVolume(
                    vwap = 1.337, 
                    obv = 1.337, 
                    volume_sma_20 = 1.337, ),
                signals = cs2cap_sdk.models.indicator_signals.IndicatorSignals(
                    rsi = '', 
                    macd = '', 
                    trend = '', 
                    bollinger = '', 
                    volatility = '', 
                    composite_score = 1.337, ),
                coverage = cs2cap_sdk.models.indicator_data_coverage.IndicatorDataCoverage(
                    candle_count = 56, 
                    first_bucket = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_bucket = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    sufficient_for = [
                        ''
                        ], 
                    insufficient_for = [
                        ''
                        ], )
            )
        else:
            return MarketIndicatorsItemData(
                item_id = 56,
                market_hash_name = '',
                provider = '',
                interval = '',
                close_price_usd = ERROR_TO_EXAMPLE_VALUE,
                momentum = cs2cap_sdk.models.indicator_momentum.IndicatorMomentum(
                    rsi_14 = 1.337, 
                    macd_line = 1.337, 
                    macd_signal = 1.337, 
                    macd_histogram = 1.337, 
                    sma_20 = 1.337, 
                    sma_50 = 1.337, 
                    sma_200 = 1.337, 
                    ema_12 = 1.337, 
                    ema_26 = 1.337, 
                    bb_upper = 1.337, 
                    bb_middle = 1.337, 
                    bb_lower = 1.337, ),
                volatility = cs2cap_sdk.models.indicator_volatility.IndicatorVolatility(
                    atr_14 = 1.337, 
                    historical_volatility_20 = 1.337, 
                    kc_upper = 1.337, 
                    kc_middle = 1.337, 
                    kc_lower = 1.337, ),
                volume = cs2cap_sdk.models.indicator_volume.IndicatorVolume(
                    vwap = 1.337, 
                    obv = 1.337, 
                    volume_sma_20 = 1.337, ),
                signals = cs2cap_sdk.models.indicator_signals.IndicatorSignals(
                    rsi = '', 
                    macd = '', 
                    trend = '', 
                    bollinger = '', 
                    volatility = '', 
                    composite_score = 1.337, ),
                coverage = cs2cap_sdk.models.indicator_data_coverage.IndicatorDataCoverage(
                    candle_count = 56, 
                    first_bucket = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_bucket = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    sufficient_for = [
                        ''
                        ], 
                    insufficient_for = [
                        ''
                        ], ),
        )
        """

    def testMarketIndicatorsItemData(self):
        """Test MarketIndicatorsItemData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
