# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.market_ranking_liquidity_item import MarketRankingLiquidityItem

class TestMarketRankingLiquidityItem(unittest.TestCase):
    """MarketRankingLiquidityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketRankingLiquidityItem:
        """Test MarketRankingLiquidityItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketRankingLiquidityItem`
        """
        model = MarketRankingLiquidityItem()
        if include_optional:
            return MarketRankingLiquidityItem(
                item_id = 56,
                market_hash_name = '',
                phase = '',
                provider = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                liquidity_score = 1.337,
                var_exec = 1.337,
                turnover = 1.337,
                breadth = 1.337,
                spread_pct = 1.337,
                dos = 1.337,
                dos_proxy = 1.337,
                used_proxy = True,
                confidence = 1.337,
                bid_anomaly = True
            )
        else:
            return MarketRankingLiquidityItem(
                item_id = 56,
                market_hash_name = '',
                provider = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                liquidity_score = 1.337,
                var_exec = 1.337,
                turnover = 1.337,
                breadth = 1.337,
                used_proxy = True,
                confidence = 1.337,
                bid_anomaly = True,
        )
        """

    def testMarketRankingLiquidityItem(self):
        """Test MarketRankingLiquidityItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
