# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.alert_definition import AlertDefinition

class TestAlertDefinition(unittest.TestCase):
    """AlertDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertDefinition:
        """Test AlertDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertDefinition`
        """
        model = AlertDefinition()
        if include_optional:
            return AlertDefinition(
                id = '',
                kind = '',
                threshold_value = ERROR_TO_EXAMPLE_VALUE,
                threshold_currency = '',
                is_enabled = True,
                last_triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                item = cs2cap_sdk.models.alert_item_summary.AlertItemSummary(
                    item_id = 56, 
                    market_hash_name = '', 
                    phase = '', )
            )
        else:
            return AlertDefinition(
                id = '',
                kind = '',
                threshold_value = ERROR_TO_EXAMPLE_VALUE,
                is_enabled = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                item = cs2cap_sdk.models.alert_item_summary.AlertItemSummary(
                    item_id = 56, 
                    market_hash_name = '', 
                    phase = '', ),
        )
        """

    def testAlertDefinition(self):
        """Test AlertDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
