# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.api.items_api import ItemsApi


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsApi()

    def tearDown(self) -> None:
        pass

    def test_get_market_ids_v1_items_market_ids_get(self) -> None:
        """Test case for get_market_ids_v1_items_market_ids_get

        Get Market Ids
        """
        pass

    def test_list_items_v1_items_get(self) -> None:
        """Test case for list_items_v1_items_get

        List Items
        """
        pass


if __name__ == '__main__':
    unittest.main()
