# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.api.sales_api import SalesApi


class TestSalesApi(unittest.TestCase):
    """SalesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SalesApi()

    def tearDown(self) -> None:
        pass

    def test_list_sales_v1_sales_get(self) -> None:
        """Test case for list_sales_v1_sales_get

        List Recent Sales
        """
        pass


if __name__ == '__main__':
    unittest.main()
