# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.models.items_paginated_response_item_out import ItemsPaginatedResponseItemOut

class TestItemsPaginatedResponseItemOut(unittest.TestCase):
    """ItemsPaginatedResponseItemOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemsPaginatedResponseItemOut:
        """Test ItemsPaginatedResponseItemOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemsPaginatedResponseItemOut`
        """
        model = ItemsPaginatedResponseItemOut()
        if include_optional:
            return ItemsPaginatedResponseItemOut(
                items = [
                    cs2cap.models.item_out.ItemOut(
                        item_id = 56, 
                        market_hash_name = '', 
                        phase = '', 
                        item_type = '', 
                        item_subtype = '', 
                        weapon_type = '', 
                        base_name = '', 
                        skin_name = '', 
                        wear_name = '', 
                        def_index = '', 
                        paint_index = 56, 
                        collection = '', 
                        crates = [
                            ''
                            ], 
                        rarity_name = '', 
                        rarity_color = '', 
                        style_name = '', 
                        is_stattrak = True, 
                        is_souvenir = True, 
                        min_float = 1.337, 
                        max_float = 1.337, 
                        image_url = '', 
                        supply = 56, )
                    ],
                pagination = cs2cap.models.items_pagination_meta.ItemsPaginationMeta(
                    limit = 0.0, 
                    offset = 0.0, 
                    total = 0.0, 
                    has_next = True, 
                    has_prev = True, 
                    next_cursor = '', )
            )
        else:
            return ItemsPaginatedResponseItemOut(
                items = [
                    cs2cap.models.item_out.ItemOut(
                        item_id = 56, 
                        market_hash_name = '', 
                        phase = '', 
                        item_type = '', 
                        item_subtype = '', 
                        weapon_type = '', 
                        base_name = '', 
                        skin_name = '', 
                        wear_name = '', 
                        def_index = '', 
                        paint_index = 56, 
                        collection = '', 
                        crates = [
                            ''
                            ], 
                        rarity_name = '', 
                        rarity_color = '', 
                        style_name = '', 
                        is_stattrak = True, 
                        is_souvenir = True, 
                        min_float = 1.337, 
                        max_float = 1.337, 
                        image_url = '', 
                        supply = 56, )
                    ],
                pagination = cs2cap.models.items_pagination_meta.ItemsPaginationMeta(
                    limit = 0.0, 
                    offset = 0.0, 
                    total = 0.0, 
                    has_next = True, 
                    has_prev = True, 
                    next_cursor = '', ),
        )
        """

    def testItemsPaginatedResponseItemOut(self):
        """Test ItemsPaginatedResponseItemOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
