# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap_sdk.models.provider_features import ProviderFeatures

class TestProviderFeatures(unittest.TestCase):
    """ProviderFeatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderFeatures:
        """Test ProviderFeatures
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderFeatures`
        """
        model = ProviderFeatures()
        if include_optional:
            return ProviderFeatures(
                has_buy_orders = True,
                has_recent_sales = True
            )
        else:
            return ProviderFeatures(
        )
        """

    def testProviderFeatures(self):
        """Test ProviderFeatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
