/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlertCreateRequest
 */
export interface AlertCreateRequest {
    /**
     * Normalized catalog item ID to monitor.
     * @type {number}
     * @memberof AlertCreateRequest
     */
    itemId: number;
    /**
     * Alert kind: price_below, price_above, or spread_exceeds.
     * @type {string}
     * @memberof AlertCreateRequest
     */
    kind: string;
    /**
     * Threshold value in alert units.
     * @type {string}
     * @memberof AlertCreateRequest
     */
    thresholdValue: string;
    /**
     * 
     * @type {string}
     * @memberof AlertCreateRequest
     */
    thresholdCurrency?: string | null;
    /**
     * Whether the alert should be enabled immediately.
     * @type {boolean}
     * @memberof AlertCreateRequest
     */
    isEnabled?: boolean;
}

/**
 * Check if a given object implements the AlertCreateRequest interface.
 */
export function instanceOfAlertCreateRequest(value: object): value is AlertCreateRequest {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('thresholdValue' in value) || value['thresholdValue'] === undefined) return false;
    return true;
}

export function AlertCreateRequestFromJSON(json: any): AlertCreateRequest {
    return AlertCreateRequestFromJSONTyped(json, false);
}

export function AlertCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'kind': json['kind'],
        'thresholdValue': json['threshold_value'],
        'thresholdCurrency': json['threshold_currency'] == null ? undefined : json['threshold_currency'],
        'isEnabled': json['is_enabled'] == null ? undefined : json['is_enabled'],
    };
}

export function AlertCreateRequestToJSON(json: any): AlertCreateRequest {
    return AlertCreateRequestToJSONTyped(json, false);
}

export function AlertCreateRequestToJSONTyped(value?: AlertCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'kind': value['kind'],
        'threshold_value': value['thresholdValue'],
        'threshold_currency': value['thresholdCurrency'],
        'is_enabled': value['isEnabled'],
    };
}

