/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlertBatchCreateResult } from './AlertBatchCreateResult';
import {
    AlertBatchCreateResultFromJSON,
    AlertBatchCreateResultFromJSONTyped,
    AlertBatchCreateResultToJSON,
    AlertBatchCreateResultToJSONTyped,
} from './AlertBatchCreateResult';

/**
 * 
 * @export
 * @interface AlertBatchCreateResponse
 */
export interface AlertBatchCreateResponse {
    /**
     * Number of alerts created successfully.
     * @type {number}
     * @memberof AlertBatchCreateResponse
     */
    created: number;
    /**
     * Number of batch items that failed inline validation.
     * @type {number}
     * @memberof AlertBatchCreateResponse
     */
    failed: number;
    /**
     * Ordered per-item outcomes matching the request payload order.
     * @type {Array<AlertBatchCreateResult>}
     * @memberof AlertBatchCreateResponse
     */
    results: Array<AlertBatchCreateResult>;
}

/**
 * Check if a given object implements the AlertBatchCreateResponse interface.
 */
export function instanceOfAlertBatchCreateResponse(value: object): value is AlertBatchCreateResponse {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function AlertBatchCreateResponseFromJSON(json: any): AlertBatchCreateResponse {
    return AlertBatchCreateResponseFromJSONTyped(json, false);
}

export function AlertBatchCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertBatchCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'failed': json['failed'],
        'results': ((json['results'] as Array<any>).map(AlertBatchCreateResultFromJSON)),
    };
}

export function AlertBatchCreateResponseToJSON(json: any): AlertBatchCreateResponse {
    return AlertBatchCreateResponseToJSONTyped(json, false);
}

export function AlertBatchCreateResponseToJSONTyped(value?: AlertBatchCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'failed': value['failed'],
        'results': ((value['results'] as Array<any>).map(AlertBatchCreateResultToJSON)),
    };
}

