/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /v1/bids/batch.
 * @export
 * @interface BatchBidsRequest
 */
export interface BatchBidsRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof BatchBidsRequest
     */
    itemIds?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BatchBidsRequest
     */
    marketHashNames?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BatchBidsRequest
     */
    providers?: Array<string> | null;
    /**
     * Target currency code for returned bids.
     * @type {string}
     * @memberof BatchBidsRequest
     */
    currency?: string;
}

/**
 * Check if a given object implements the BatchBidsRequest interface.
 */
export function instanceOfBatchBidsRequest(value: object): value is BatchBidsRequest {
    return true;
}

export function BatchBidsRequestFromJSON(json: any): BatchBidsRequest {
    return BatchBidsRequestFromJSONTyped(json, false);
}

export function BatchBidsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchBidsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemIds': json['item_ids'] == null ? undefined : json['item_ids'],
        'marketHashNames': json['market_hash_names'] == null ? undefined : json['market_hash_names'],
        'providers': json['providers'] == null ? undefined : json['providers'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function BatchBidsRequestToJSON(json: any): BatchBidsRequest {
    return BatchBidsRequestToJSONTyped(json, false);
}

export function BatchBidsRequestToJSONTyped(value?: BatchBidsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_ids': value['itemIds'],
        'market_hash_names': value['marketHashNames'],
        'providers': value['providers'],
        'currency': value['currency'],
    };
}

