/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BidsMeta } from './BidsMeta';
import {
    BidsMetaFromJSON,
    BidsMetaFromJSONTyped,
    BidsMetaToJSON,
    BidsMetaToJSONTyped,
} from './BidsMeta';
import type { BuyOrderItem } from './BuyOrderItem';
import {
    BuyOrderItemFromJSON,
    BuyOrderItemFromJSONTyped,
    BuyOrderItemToJSON,
    BuyOrderItemToJSONTyped,
} from './BuyOrderItem';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * Bids response with metadata and pagination.
 * @export
 * @interface BidsResponse
 */
export interface BidsResponse {
    /**
     * Response metadata for this payload.
     * @type {BidsMeta}
     * @memberof BidsResponse
     */
    meta: BidsMeta;
    /**
     * List of returned items.
     * @type {Array<BuyOrderItem>}
     * @memberof BidsResponse
     */
    items: Array<BuyOrderItem>;
    /**
     * Pagination metadata for this response.
     * @type {PaginationMeta}
     * @memberof BidsResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the BidsResponse interface.
 */
export function instanceOfBidsResponse(value: object): value is BidsResponse {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function BidsResponseFromJSON(json: any): BidsResponse {
    return BidsResponseFromJSONTyped(json, false);
}

export function BidsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BidsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': BidsMetaFromJSON(json['meta']),
        'items': ((json['items'] as Array<any>).map(BuyOrderItemFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function BidsResponseToJSON(json: any): BidsResponse {
    return BidsResponseToJSONTyped(json, false);
}

export function BidsResponseToJSONTyped(value?: BidsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': BidsMetaToJSON(value['meta']),
        'items': ((value['items'] as Array<any>).map(BuyOrderItemToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

