/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Filter metadata for bids endpoint.
 * @export
 * @interface BidsFilterMeta
 */
export interface BidsFilterMeta {
    /**
     * 
     * @type {number}
     * @memberof BidsFilterMeta
     */
    itemId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BidsFilterMeta
     */
    marketHashName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BidsFilterMeta
     */
    phase?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BidsFilterMeta
     */
    requestedProviders?: Array<string> | null;
}

/**
 * Check if a given object implements the BidsFilterMeta interface.
 */
export function instanceOfBidsFilterMeta(value: object): value is BidsFilterMeta {
    return true;
}

export function BidsFilterMetaFromJSON(json: any): BidsFilterMeta {
    return BidsFilterMetaFromJSONTyped(json, false);
}

export function BidsFilterMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BidsFilterMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'] == null ? undefined : json['item_id'],
        'marketHashName': json['market_hash_name'] == null ? undefined : json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'requestedProviders': json['requested_providers'] == null ? undefined : json['requested_providers'],
    };
}

export function BidsFilterMetaToJSON(json: any): BidsFilterMeta {
    return BidsFilterMetaToJSONTyped(json, false);
}

export function BidsFilterMetaToJSONTyped(value?: BidsFilterMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'requested_providers': value['requestedProviders'],
    };
}

