/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Provider keys that support buy orders.
 * @export
 */
export const BuyOrderProvider = {
    Buff163: 'buff163',
    Buffmarket: 'buffmarket',
    C5: 'c5',
    Csfloat: 'csfloat',
    Dmarket: 'dmarket',
    Ecosteam: 'ecosteam',
    Marketcsgo: 'marketcsgo',
    Steam: 'steam',
    Waxpeer: 'waxpeer',
    Whitemarket: 'whitemarket',
    Youpin: 'youpin'
} as const;
export type BuyOrderProvider = typeof BuyOrderProvider[keyof typeof BuyOrderProvider];


export function instanceOfBuyOrderProvider(value: any): boolean {
    for (const key in BuyOrderProvider) {
        if (Object.prototype.hasOwnProperty.call(BuyOrderProvider, key)) {
            if (BuyOrderProvider[key as keyof typeof BuyOrderProvider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BuyOrderProviderFromJSON(json: any): BuyOrderProvider {
    return BuyOrderProviderFromJSONTyped(json, false);
}

export function BuyOrderProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuyOrderProvider {
    return json as BuyOrderProvider;
}

export function BuyOrderProviderToJSON(value?: BuyOrderProvider | null): any {
    return value as any;
}

export function BuyOrderProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): BuyOrderProvider {
    return value as BuyOrderProvider;
}

