/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Charm/keychain information.
 * @export
 * @interface CharmInfo
 */
export interface CharmInfo {
    /**
     * Display name for this entity.
     * @type {string}
     * @memberof CharmInfo
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CharmInfo
     */
    patternId?: number | null;
}

/**
 * Check if a given object implements the CharmInfo interface.
 */
export function instanceOfCharmInfo(value: object): value is CharmInfo {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CharmInfoFromJSON(json: any): CharmInfo {
    return CharmInfoFromJSONTyped(json, false);
}

export function CharmInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharmInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'patternId': json['pattern_id'] == null ? undefined : json['pattern_id'],
    };
}

export function CharmInfoToJSON(json: any): CharmInfo {
    return CharmInfoToJSONTyped(json, false);
}

export function CharmInfoToJSONTyped(value?: CharmInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'pattern_id': value['patternId'],
    };
}

