/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { ChildAPIKeyDetailResponse } from './ChildAPIKeyDetailResponse';
import {
    ChildAPIKeyDetailResponseFromJSON,
    ChildAPIKeyDetailResponseFromJSONTyped,
    ChildAPIKeyDetailResponseToJSON,
    ChildAPIKeyDetailResponseToJSONTyped,
} from './ChildAPIKeyDetailResponse';

/**
 * Paginated child-key listing.
 * @export
 * @interface ChildAPIKeyListResponse
 */
export interface ChildAPIKeyListResponse {
    /**
     * Child API keys.
     * @type {Array<ChildAPIKeyDetailResponse>}
     * @memberof ChildAPIKeyListResponse
     */
    keys: Array<ChildAPIKeyDetailResponse>;
    /**
     * Offset pagination metadata.
     * @type {PaginationMeta}
     * @memberof ChildAPIKeyListResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the ChildAPIKeyListResponse interface.
 */
export function instanceOfChildAPIKeyListResponse(value: object): value is ChildAPIKeyListResponse {
    if (!('keys' in value) || value['keys'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ChildAPIKeyListResponseFromJSON(json: any): ChildAPIKeyListResponse {
    return ChildAPIKeyListResponseFromJSONTyped(json, false);
}

export function ChildAPIKeyListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildAPIKeyListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': ((json['keys'] as Array<any>).map(ChildAPIKeyDetailResponseFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function ChildAPIKeyListResponseToJSON(json: any): ChildAPIKeyListResponse {
    return ChildAPIKeyListResponseToJSONTyped(json, false);
}

export function ChildAPIKeyListResponseToJSONTyped(value?: ChildAPIKeyListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': ((value['keys'] as Array<any>).map(ChildAPIKeyDetailResponseToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

