/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Update mutable child-key fields.
 * @export
 * @interface ChildAPIKeyUpdateRequest
 */
export interface ChildAPIKeyUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ChildAPIKeyUpdateRequest
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChildAPIKeyUpdateRequest
     */
    quotaRequestsPerMonthOverride?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChildAPIKeyUpdateRequest
     */
    rateRequestsPerMinuteOverride?: number | null;
}

/**
 * Check if a given object implements the ChildAPIKeyUpdateRequest interface.
 */
export function instanceOfChildAPIKeyUpdateRequest(value: object): value is ChildAPIKeyUpdateRequest {
    return true;
}

export function ChildAPIKeyUpdateRequestFromJSON(json: any): ChildAPIKeyUpdateRequest {
    return ChildAPIKeyUpdateRequestFromJSONTyped(json, false);
}

export function ChildAPIKeyUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildAPIKeyUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'quotaRequestsPerMonthOverride': json['quota_requests_per_month_override'] == null ? undefined : json['quota_requests_per_month_override'],
        'rateRequestsPerMinuteOverride': json['rate_requests_per_minute_override'] == null ? undefined : json['rate_requests_per_minute_override'],
    };
}

export function ChildAPIKeyUpdateRequestToJSON(json: any): ChildAPIKeyUpdateRequest {
    return ChildAPIKeyUpdateRequestToJSONTyped(json, false);
}

export function ChildAPIKeyUpdateRequestToJSONTyped(value?: ChildAPIKeyUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'quota_requests_per_month_override': value['quotaRequestsPerMonthOverride'],
        'rate_requests_per_minute_override': value['rateRequestsPerMinuteOverride'],
    };
}

