/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIKeyInfo } from './APIKeyInfo';
import {
    APIKeyInfoFromJSON,
    APIKeyInfoFromJSONTyped,
    APIKeyInfoToJSON,
    APIKeyInfoToJSONTyped,
} from './APIKeyInfo';

/**
 * One child key plus current-month usage summary.
 * @export
 * @interface ChildAPIKeyDetailResponse
 */
export interface ChildAPIKeyDetailResponse {
    /**
     * Child API key metadata.
     * @type {APIKeyInfo}
     * @memberof ChildAPIKeyDetailResponse
     */
    key: APIKeyInfo;
    /**
     * Current-month request count for this child key.
     * @type {number}
     * @memberof ChildAPIKeyDetailResponse
     */
    requestsThisMonth: number;
}

/**
 * Check if a given object implements the ChildAPIKeyDetailResponse interface.
 */
export function instanceOfChildAPIKeyDetailResponse(value: object): value is ChildAPIKeyDetailResponse {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('requestsThisMonth' in value) || value['requestsThisMonth'] === undefined) return false;
    return true;
}

export function ChildAPIKeyDetailResponseFromJSON(json: any): ChildAPIKeyDetailResponse {
    return ChildAPIKeyDetailResponseFromJSONTyped(json, false);
}

export function ChildAPIKeyDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildAPIKeyDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'key': APIKeyInfoFromJSON(json['key']),
        'requestsThisMonth': json['requests_this_month'],
    };
}

export function ChildAPIKeyDetailResponseToJSON(json: any): ChildAPIKeyDetailResponse {
    return ChildAPIKeyDetailResponseToJSONTyped(json, false);
}

export function ChildAPIKeyDetailResponseToJSONTyped(value?: ChildAPIKeyDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': APIKeyInfoToJSON(value['key']),
        'requests_this_month': value['requestsThisMonth'],
    };
}

