/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Volatility indicator values.
 * @export
 * @interface IndicatorVolatility
 */
export interface IndicatorVolatility {
    /**
     * 
     * @type {number}
     * @memberof IndicatorVolatility
     */
    atr14?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IndicatorVolatility
     */
    historicalVolatility20?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IndicatorVolatility
     */
    kcUpper?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IndicatorVolatility
     */
    kcMiddle?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IndicatorVolatility
     */
    kcLower?: number | null;
}

/**
 * Check if a given object implements the IndicatorVolatility interface.
 */
export function instanceOfIndicatorVolatility(value: object): value is IndicatorVolatility {
    return true;
}

export function IndicatorVolatilityFromJSON(json: any): IndicatorVolatility {
    return IndicatorVolatilityFromJSONTyped(json, false);
}

export function IndicatorVolatilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndicatorVolatility {
    if (json == null) {
        return json;
    }
    return {
        
        'atr14': json['atr_14'] == null ? undefined : json['atr_14'],
        'historicalVolatility20': json['historical_volatility_20'] == null ? undefined : json['historical_volatility_20'],
        'kcUpper': json['kc_upper'] == null ? undefined : json['kc_upper'],
        'kcMiddle': json['kc_middle'] == null ? undefined : json['kc_middle'],
        'kcLower': json['kc_lower'] == null ? undefined : json['kc_lower'],
    };
}

export function IndicatorVolatilityToJSON(json: any): IndicatorVolatility {
    return IndicatorVolatilityToJSONTyped(json, false);
}

export function IndicatorVolatilityToJSONTyped(value?: IndicatorVolatility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'atr_14': value['atr14'],
        'historical_volatility_20': value['historicalVolatility20'],
        'kc_upper': value['kcUpper'],
        'kc_middle': value['kcMiddle'],
        'kc_lower': value['kcLower'],
    };
}

