/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * In-game inspect link and screenshot URLs.
 * @export
 * @interface InspectInfo
 */
export interface InspectInfo {
    /**
     * 
     * @type {string}
     * @memberof InspectInfo
     */
    inGame?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InspectInfo
     */
    screenshotFront?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InspectInfo
     */
    screenshotBack?: string | null;
}

/**
 * Check if a given object implements the InspectInfo interface.
 */
export function instanceOfInspectInfo(value: object): value is InspectInfo {
    return true;
}

export function InspectInfoFromJSON(json: any): InspectInfo {
    return InspectInfoFromJSONTyped(json, false);
}

export function InspectInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'inGame': json['in_game'] == null ? undefined : json['in_game'],
        'screenshotFront': json['screenshot_front'] == null ? undefined : json['screenshot_front'],
        'screenshotBack': json['screenshot_back'] == null ? undefined : json['screenshot_back'],
    };
}

export function InspectInfoToJSON(json: any): InspectInfo {
    return InspectInfoToJSONTyped(json, false);
}

export function InspectInfoToJSONTyped(value?: InspectInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'in_game': value['inGame'],
        'screenshot_front': value['screenshotFront'],
        'screenshot_back': value['screenshotBack'],
    };
}

