/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketRankingVolumeItem } from './MarketRankingVolumeItem';
import {
    MarketRankingVolumeItemFromJSON,
    MarketRankingVolumeItemFromJSONTyped,
    MarketRankingVolumeItemToJSON,
    MarketRankingVolumeItemToJSONTyped,
} from './MarketRankingVolumeItem';
import type { MarketRankingLiquidityItem } from './MarketRankingLiquidityItem';
import {
    MarketRankingLiquidityItemFromJSON,
    MarketRankingLiquidityItemFromJSONTyped,
    MarketRankingLiquidityItemToJSON,
    MarketRankingLiquidityItemToJSONTyped,
} from './MarketRankingLiquidityItem';
import type { MarketRankingVolatilityItem } from './MarketRankingVolatilityItem';
import {
    MarketRankingVolatilityItemFromJSON,
    MarketRankingVolatilityItemFromJSONTyped,
    MarketRankingVolatilityItemToJSON,
    MarketRankingVolatilityItemToJSONTyped,
} from './MarketRankingVolatilityItem';

/**
 * 
 * @export
 * @interface ItemsInner
 */
export interface ItemsInner {
    /**
     * Normalized catalog item ID used by this API.
     * @type {number}
     * @memberof ItemsInner
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof ItemsInner
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof ItemsInner
     */
    phase?: string;
    /**
     * Provider key used by this API.
     * @type {string}
     * @memberof ItemsInner
     */
    provider: string;
    /**
     * ISO 8601 UTC timestamp when this record was last ingested or processed.
     * @type {Date}
     * @memberof ItemsInner
     */
    lastUpdated: Date;
    /**
     * Volatility score value.
     * @type {number}
     * @memberof ItemsInner
     */
    volatilityScore: number;
    /**
     * USD-denominated value for current price.
     * @type {string}
     * @memberof ItemsInner
     */
    currentPriceUsd: string;
    /**
     * USD-denominated value for min price.
     * @type {string}
     * @memberof ItemsInner
     */
    minPriceUsd: string;
    /**
     * USD-denominated value for max price.
     * @type {string}
     * @memberof ItemsInner
     */
    maxPriceUsd: string;
    /**
     * USD-denominated value for std dev.
     * @type {string}
     * @memberof ItemsInner
     */
    stdDevUsd: string;
    /**
     * Sample count value.
     * @type {number}
     * @memberof ItemsInner
     */
    sampleCount: number;
    /**
     * Depletion activity volume over the last 24 hours.
     * @type {number}
     * @memberof ItemsInner
     */
    volume24h: number;
    /**
     * Depletion activity volume over the last 7 days.
     * @type {number}
     * @memberof ItemsInner
     */
    volume7d: number;
    /**
     * Depletion activity volume over the last 30 days.
     * @type {number}
     * @memberof ItemsInner
     */
    volume30d: number;
    /**
     * USD-denominated value for total value 24h.
     * @type {string}
     * @memberof ItemsInner
     */
    totalValue24hUsd: string;
    /**
     * Liquidity score value.
     * @type {number}
     * @memberof ItemsInner
     */
    liquidityScore: number;
    /**
     * Exec value.
     * @type {number}
     * @memberof ItemsInner
     */
    exec: number;
    /**
     * Turnover value.
     * @type {number}
     * @memberof ItemsInner
     */
    turnover: number;
    /**
     * Breadth value.
     * @type {number}
     * @memberof ItemsInner
     */
    breadth: number;
    /**
     * 
     * @type {number}
     * @memberof ItemsInner
     */
    spreadPct?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemsInner
     */
    dos?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemsInner
     */
    dosProxy?: number;
    /**
     * Used proxy value.
     * @type {boolean}
     * @memberof ItemsInner
     */
    usedProxy: boolean;
    /**
     * Confidence value.
     * @type {number}
     * @memberof ItemsInner
     */
    confidence: number;
    /**
     * Bid anomaly value.
     * @type {boolean}
     * @memberof ItemsInner
     */
    bidAnomaly: boolean;
}

/**
 * Check if a given object implements the ItemsInner interface.
 */
export function instanceOfItemsInner(value: object): value is ItemsInner {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    if (!('volatilityScore' in value) || value['volatilityScore'] === undefined) return false;
    if (!('currentPriceUsd' in value) || value['currentPriceUsd'] === undefined) return false;
    if (!('minPriceUsd' in value) || value['minPriceUsd'] === undefined) return false;
    if (!('maxPriceUsd' in value) || value['maxPriceUsd'] === undefined) return false;
    if (!('stdDevUsd' in value) || value['stdDevUsd'] === undefined) return false;
    if (!('sampleCount' in value) || value['sampleCount'] === undefined) return false;
    if (!('volume24h' in value) || value['volume24h'] === undefined) return false;
    if (!('volume7d' in value) || value['volume7d'] === undefined) return false;
    if (!('volume30d' in value) || value['volume30d'] === undefined) return false;
    if (!('totalValue24hUsd' in value) || value['totalValue24hUsd'] === undefined) return false;
    if (!('liquidityScore' in value) || value['liquidityScore'] === undefined) return false;
    if (!('exec' in value) || value['exec'] === undefined) return false;
    if (!('turnover' in value) || value['turnover'] === undefined) return false;
    if (!('breadth' in value) || value['breadth'] === undefined) return false;
    if (!('usedProxy' in value) || value['usedProxy'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('bidAnomaly' in value) || value['bidAnomaly'] === undefined) return false;
    return true;
}

export function ItemsInnerFromJSON(json: any): ItemsInner {
    return ItemsInnerFromJSONTyped(json, false);
}

export function ItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'provider': json['provider'],
        'lastUpdated': (new Date(json['last_updated'])),
        'volatilityScore': json['volatility_score'],
        'currentPriceUsd': json['current_price_usd'],
        'minPriceUsd': json['min_price_usd'],
        'maxPriceUsd': json['max_price_usd'],
        'stdDevUsd': json['std_dev_usd'],
        'sampleCount': json['sample_count'],
        'volume24h': json['volume_24h'],
        'volume7d': json['volume_7d'],
        'volume30d': json['volume_30d'],
        'totalValue24hUsd': json['total_value_24h_usd'],
        'liquidityScore': json['liquidity_score'],
        'exec': json['exec'],
        'turnover': json['turnover'],
        'breadth': json['breadth'],
        'spreadPct': json['spread_pct'] == null ? undefined : json['spread_pct'],
        'dos': json['dos'] == null ? undefined : json['dos'],
        'dosProxy': json['dos_proxy'] == null ? undefined : json['dos_proxy'],
        'usedProxy': json['used_proxy'],
        'confidence': json['confidence'],
        'bidAnomaly': json['bid_anomaly'],
    };
}

export function ItemsInnerToJSON(json: any): ItemsInner {
    return ItemsInnerToJSONTyped(json, false);
}

export function ItemsInnerToJSONTyped(value?: ItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'provider': value['provider'],
        'last_updated': value['lastUpdated'].toISOString(),
        'volatility_score': value['volatilityScore'],
        'current_price_usd': value['currentPriceUsd'],
        'min_price_usd': value['minPriceUsd'],
        'max_price_usd': value['maxPriceUsd'],
        'std_dev_usd': value['stdDevUsd'],
        'sample_count': value['sampleCount'],
        'volume_24h': value['volume24h'],
        'volume_7d': value['volume7d'],
        'volume_30d': value['volume30d'],
        'total_value_24h_usd': value['totalValue24hUsd'],
        'liquidity_score': value['liquidityScore'],
        'exec': value['exec'],
        'turnover': value['turnover'],
        'breadth': value['breadth'],
        'spread_pct': value['spreadPct'],
        'dos': value['dos'],
        'dos_proxy': value['dosProxy'],
        'used_proxy': value['usedProxy'],
        'confidence': value['confidence'],
        'bid_anomaly': value['bidAnomaly'],
    };
}

