/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemsCatalogSummary
 */
export interface ItemsCatalogSummary {
    /**
     * Total number of catalog items currently available.
     * @type {number}
     * @memberof ItemsCatalogSummary
     */
    totalItems: number;
}

/**
 * Check if a given object implements the ItemsCatalogSummary interface.
 */
export function instanceOfItemsCatalogSummary(value: object): value is ItemsCatalogSummary {
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    return true;
}

export function ItemsCatalogSummaryFromJSON(json: any): ItemsCatalogSummary {
    return ItemsCatalogSummaryFromJSONTyped(json, false);
}

export function ItemsCatalogSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemsCatalogSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['total_items'],
    };
}

export function ItemsCatalogSummaryToJSON(json: any): ItemsCatalogSummary {
    return ItemsCatalogSummaryToJSONTyped(json, false);
}

export function ItemsCatalogSummaryToJSONTyped(value?: ItemsCatalogSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_items': value['totalItems'],
    };
}

