/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketTimeWindowMeta } from './MarketTimeWindowMeta';
import {
    MarketTimeWindowMetaFromJSON,
    MarketTimeWindowMetaFromJSONTyped,
    MarketTimeWindowMetaToJSON,
    MarketTimeWindowMetaToJSONTyped,
} from './MarketTimeWindowMeta';

/**
 * Metadata for rankings endpoint.
 * @export
 * @interface MarketRankingMeta
 */
export interface MarketRankingMeta {
    /**
     * ISO 8601 UTC timestamp when this response was generated.
     * @type {Date}
     * @memberof MarketRankingMeta
     */
    generatedAt: Date;
    /**
     * Primary data source used to build this response.
     * @type {MarketRankingMetaDataSourceEnum}
     * @memberof MarketRankingMeta
     */
    dataSource: MarketRankingMetaDataSourceEnum;
    /**
     * Estimated freshness of source data in seconds.
     * @type {number}
     * @memberof MarketRankingMeta
     */
    freshnessSec: number;
    /**
     * 
     * @type {MarketTimeWindowMeta}
     * @memberof MarketRankingMeta
     */
    window?: MarketTimeWindowMeta | null;
    /**
     * Metric value.
     * @type {MarketRankingMetaMetricEnum}
     * @memberof MarketRankingMeta
     */
    metric: MarketRankingMetaMetricEnum;
}


/**
 * @export
 */
export const MarketRankingMetaDataSourceEnum = {
    Cache: 'cache',
    Live: 'live',
    Mixed: 'mixed'
} as const;
export type MarketRankingMetaDataSourceEnum = typeof MarketRankingMetaDataSourceEnum[keyof typeof MarketRankingMetaDataSourceEnum];

/**
 * @export
 */
export const MarketRankingMetaMetricEnum = {
    Volatility: 'volatility',
    Volume: 'volume',
    Liquidity: 'liquidity'
} as const;
export type MarketRankingMetaMetricEnum = typeof MarketRankingMetaMetricEnum[keyof typeof MarketRankingMetaMetricEnum];


/**
 * Check if a given object implements the MarketRankingMeta interface.
 */
export function instanceOfMarketRankingMeta(value: object): value is MarketRankingMeta {
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('dataSource' in value) || value['dataSource'] === undefined) return false;
    if (!('freshnessSec' in value) || value['freshnessSec'] === undefined) return false;
    if (!('metric' in value) || value['metric'] === undefined) return false;
    return true;
}

export function MarketRankingMetaFromJSON(json: any): MarketRankingMeta {
    return MarketRankingMetaFromJSONTyped(json, false);
}

export function MarketRankingMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketRankingMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': (new Date(json['generated_at'])),
        'dataSource': json['data_source'],
        'freshnessSec': json['freshness_sec'],
        'window': json['window'] == null ? undefined : MarketTimeWindowMetaFromJSON(json['window']),
        'metric': json['metric'],
    };
}

export function MarketRankingMetaToJSON(json: any): MarketRankingMeta {
    return MarketRankingMetaToJSONTyped(json, false);
}

export function MarketRankingMetaToJSONTyped(value?: MarketRankingMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_at': value['generatedAt'].toISOString(),
        'data_source': value['dataSource'],
        'freshness_sec': value['freshnessSec'],
        'window': MarketTimeWindowMetaToJSON(value['window']),
        'metric': value['metric'],
    };
}

