/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketIndexGroup } from './MarketIndexGroup';
import {
    MarketIndexGroupFromJSON,
    MarketIndexGroupFromJSONTyped,
    MarketIndexGroupToJSON,
    MarketIndexGroupToJSONTyped,
} from './MarketIndexGroup';

/**
 * Payload for /v1/market/indices.
 * @export
 * @interface MarketIndicesData
 */
export interface MarketIndicesData {
    /**
     * Money amount as a decimal string in USD major units (for example "25.82").
     * @type {string}
     * @memberof MarketIndicesData
     */
    totalMarketcapUsd: string;
    /**
     * Category groups sorted by market cap descending.
     * @type {Array<MarketIndexGroup>}
     * @memberof MarketIndicesData
     */
    groups: Array<MarketIndexGroup>;
}

/**
 * Check if a given object implements the MarketIndicesData interface.
 */
export function instanceOfMarketIndicesData(value: object): value is MarketIndicesData {
    if (!('totalMarketcapUsd' in value) || value['totalMarketcapUsd'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    return true;
}

export function MarketIndicesDataFromJSON(json: any): MarketIndicesData {
    return MarketIndicesDataFromJSONTyped(json, false);
}

export function MarketIndicesDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketIndicesData {
    if (json == null) {
        return json;
    }
    return {
        
        'totalMarketcapUsd': json['total_marketcap_usd'],
        'groups': ((json['groups'] as Array<any>).map(MarketIndexGroupFromJSON)),
    };
}

export function MarketIndicesDataToJSON(json: any): MarketIndicesData {
    return MarketIndicesDataToJSONTyped(json, false);
}

export function MarketIndicesDataToJSONTyped(value?: MarketIndicesData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_marketcap_usd': value['totalMarketcapUsd'],
        'groups': ((value['groups'] as Array<any>).map(MarketIndexGroupToJSON)),
    };
}

