/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Mover payload in canonical USD units.
 * @export
 * @interface MarketMoverItem
 */
export interface MarketMoverItem {
    /**
     * Normalized catalog item ID used by this API.
     * @type {number}
     * @memberof MarketMoverItem
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof MarketMoverItem
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof MarketMoverItem
     */
    phase?: string | null;
    /**
     * Provider key used by this API.
     * @type {string}
     * @memberof MarketMoverItem
     */
    provider: string;
    /**
     * USD-denominated value for current price.
     * @type {string}
     * @memberof MarketMoverItem
     */
    currentPriceUsd: string;
    /**
     * USD-denominated value for previous price.
     * @type {string}
     * @memberof MarketMoverItem
     */
    previousPriceUsd: string;
    /**
     * USD-denominated value for price change.
     * @type {string}
     * @memberof MarketMoverItem
     */
    priceChangeUsd: string;
    /**
     * Percentage value for price change.
     * @type {number}
     * @memberof MarketMoverItem
     */
    priceChangePct: number;
    /**
     * Depletion activity volume over the selected window.
     * @type {number}
     * @memberof MarketMoverItem
     */
    volume: number;
    /**
     * ISO 8601 UTC timestamp when this record was last ingested or processed.
     * @type {Date}
     * @memberof MarketMoverItem
     */
    lastUpdated: Date;
}

/**
 * Check if a given object implements the MarketMoverItem interface.
 */
export function instanceOfMarketMoverItem(value: object): value is MarketMoverItem {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('currentPriceUsd' in value) || value['currentPriceUsd'] === undefined) return false;
    if (!('previousPriceUsd' in value) || value['previousPriceUsd'] === undefined) return false;
    if (!('priceChangeUsd' in value) || value['priceChangeUsd'] === undefined) return false;
    if (!('priceChangePct' in value) || value['priceChangePct'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    return true;
}

export function MarketMoverItemFromJSON(json: any): MarketMoverItem {
    return MarketMoverItemFromJSONTyped(json, false);
}

export function MarketMoverItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketMoverItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'provider': json['provider'],
        'currentPriceUsd': json['current_price_usd'],
        'previousPriceUsd': json['previous_price_usd'],
        'priceChangeUsd': json['price_change_usd'],
        'priceChangePct': json['price_change_pct'],
        'volume': json['volume'],
        'lastUpdated': (new Date(json['last_updated'])),
    };
}

export function MarketMoverItemToJSON(json: any): MarketMoverItem {
    return MarketMoverItemToJSONTyped(json, false);
}

export function MarketMoverItemToJSONTyped(value?: MarketMoverItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'provider': value['provider'],
        'current_price_usd': value['currentPriceUsd'],
        'previous_price_usd': value['previousPriceUsd'],
        'price_change_usd': value['priceChangeUsd'],
        'price_change_pct': value['priceChangePct'],
        'volume': value['volume'],
        'last_updated': value['lastUpdated'].toISOString(),
    };
}

