/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketMoverItem } from './MarketMoverItem';
import {
    MarketMoverItemFromJSON,
    MarketMoverItemFromJSONTyped,
    MarketMoverItemToJSON,
    MarketMoverItemToJSONTyped,
} from './MarketMoverItem';

/**
 * Movers endpoint payload.
 * @export
 * @interface MarketMoversData
 */
export interface MarketMoversData {
    /**
     * Items with positive movement for the selected window.
     * @type {Array<MarketMoverItem>}
     * @memberof MarketMoversData
     */
    gainers: Array<MarketMoverItem>;
    /**
     * Items with negative movement for the selected window.
     * @type {Array<MarketMoverItem>}
     * @memberof MarketMoversData
     */
    losers: Array<MarketMoverItem>;
}

/**
 * Check if a given object implements the MarketMoversData interface.
 */
export function instanceOfMarketMoversData(value: object): value is MarketMoversData {
    if (!('gainers' in value) || value['gainers'] === undefined) return false;
    if (!('losers' in value) || value['losers'] === undefined) return false;
    return true;
}

export function MarketMoversDataFromJSON(json: any): MarketMoversData {
    return MarketMoversDataFromJSONTyped(json, false);
}

export function MarketMoversDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketMoversData {
    if (json == null) {
        return json;
    }
    return {
        
        'gainers': ((json['gainers'] as Array<any>).map(MarketMoverItemFromJSON)),
        'losers': ((json['losers'] as Array<any>).map(MarketMoverItemFromJSON)),
    };
}

export function MarketMoversDataToJSON(json: any): MarketMoversData {
    return MarketMoversDataToJSONTyped(json, false);
}

export function MarketMoversDataToJSONTyped(value?: MarketMoversData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gainers': ((value['gainers'] as Array<any>).map(MarketMoverItemToJSON)),
        'losers': ((value['losers'] as Array<any>).map(MarketMoverItemToJSON)),
    };
}

