/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketTimeWindowMeta } from './MarketTimeWindowMeta';
import {
    MarketTimeWindowMetaFromJSON,
    MarketTimeWindowMetaFromJSONTyped,
    MarketTimeWindowMetaToJSON,
    MarketTimeWindowMetaToJSONTyped,
} from './MarketTimeWindowMeta';

/**
 * Shared metadata for redesigned market endpoints.
 * @export
 * @interface MarketMeta
 */
export interface MarketMeta {
    /**
     * ISO 8601 UTC timestamp when this response was generated.
     * @type {Date}
     * @memberof MarketMeta
     */
    generatedAt: Date;
    /**
     * Primary data source used to build this response.
     * @type {MarketMetaDataSourceEnum}
     * @memberof MarketMeta
     */
    dataSource: MarketMetaDataSourceEnum;
    /**
     * Estimated freshness of source data in seconds.
     * @type {number}
     * @memberof MarketMeta
     */
    freshnessSec: number;
    /**
     * 
     * @type {MarketTimeWindowMeta}
     * @memberof MarketMeta
     */
    window?: MarketTimeWindowMeta | null;
}


/**
 * @export
 */
export const MarketMetaDataSourceEnum = {
    Cache: 'cache',
    Live: 'live',
    Mixed: 'mixed'
} as const;
export type MarketMetaDataSourceEnum = typeof MarketMetaDataSourceEnum[keyof typeof MarketMetaDataSourceEnum];


/**
 * Check if a given object implements the MarketMeta interface.
 */
export function instanceOfMarketMeta(value: object): value is MarketMeta {
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('dataSource' in value) || value['dataSource'] === undefined) return false;
    if (!('freshnessSec' in value) || value['freshnessSec'] === undefined) return false;
    return true;
}

export function MarketMetaFromJSON(json: any): MarketMeta {
    return MarketMetaFromJSONTyped(json, false);
}

export function MarketMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': (new Date(json['generated_at'])),
        'dataSource': json['data_source'],
        'freshnessSec': json['freshness_sec'],
        'window': json['window'] == null ? undefined : MarketTimeWindowMetaFromJSON(json['window']),
    };
}

export function MarketMetaToJSON(json: any): MarketMeta {
    return MarketMetaToJSONTyped(json, false);
}

export function MarketMetaToJSONTyped(value?: MarketMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_at': value['generatedAt'].toISOString(),
        'data_source': value['dataSource'],
        'freshness_sec': value['freshnessSec'],
        'window': MarketTimeWindowMetaToJSON(value['window']),
    };
}

