/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketTimeWindowMeta } from './MarketTimeWindowMeta';
import {
    MarketTimeWindowMetaFromJSON,
    MarketTimeWindowMetaFromJSONTyped,
    MarketTimeWindowMetaToJSON,
    MarketTimeWindowMetaToJSONTyped,
} from './MarketTimeWindowMeta';

/**
 * Metadata for indicators endpoint.
 * @export
 * @interface MarketIndicatorsMeta
 */
export interface MarketIndicatorsMeta {
    /**
     * ISO 8601 UTC timestamp when this response was generated.
     * @type {Date}
     * @memberof MarketIndicatorsMeta
     */
    generatedAt: Date;
    /**
     * Primary data source used to build this response.
     * @type {MarketIndicatorsMetaDataSourceEnum}
     * @memberof MarketIndicatorsMeta
     */
    dataSource: MarketIndicatorsMetaDataSourceEnum;
    /**
     * Estimated freshness of source data in seconds.
     * @type {number}
     * @memberof MarketIndicatorsMeta
     */
    freshnessSec: number;
    /**
     * 
     * @type {MarketTimeWindowMeta}
     * @memberof MarketIndicatorsMeta
     */
    window?: MarketTimeWindowMeta | null;
    /**
     * Interval value.
     * @type {string}
     * @memberof MarketIndicatorsMeta
     */
    interval: string;
    /**
     * 
     * @type {string}
     * @memberof MarketIndicatorsMeta
     */
    provider?: string | null;
}


/**
 * @export
 */
export const MarketIndicatorsMetaDataSourceEnum = {
    Cache: 'cache',
    Live: 'live',
    Mixed: 'mixed'
} as const;
export type MarketIndicatorsMetaDataSourceEnum = typeof MarketIndicatorsMetaDataSourceEnum[keyof typeof MarketIndicatorsMetaDataSourceEnum];


/**
 * Check if a given object implements the MarketIndicatorsMeta interface.
 */
export function instanceOfMarketIndicatorsMeta(value: object): value is MarketIndicatorsMeta {
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('dataSource' in value) || value['dataSource'] === undefined) return false;
    if (!('freshnessSec' in value) || value['freshnessSec'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    return true;
}

export function MarketIndicatorsMetaFromJSON(json: any): MarketIndicatorsMeta {
    return MarketIndicatorsMetaFromJSONTyped(json, false);
}

export function MarketIndicatorsMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketIndicatorsMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': (new Date(json['generated_at'])),
        'dataSource': json['data_source'],
        'freshnessSec': json['freshness_sec'],
        'window': json['window'] == null ? undefined : MarketTimeWindowMetaFromJSON(json['window']),
        'interval': json['interval'],
        'provider': json['provider'] == null ? undefined : json['provider'],
    };
}

export function MarketIndicatorsMetaToJSON(json: any): MarketIndicatorsMeta {
    return MarketIndicatorsMetaToJSONTyped(json, false);
}

export function MarketIndicatorsMetaToJSONTyped(value?: MarketIndicatorsMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_at': value['generatedAt'].toISOString(),
        'data_source': value['dataSource'],
        'freshness_sec': value['freshnessSec'],
        'window': MarketTimeWindowMetaToJSON(value['window']),
        'interval': value['interval'],
        'provider': value['provider'],
    };
}

