/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketIndexesMeta } from './MarketIndexesMeta';
import {
    MarketIndexesMetaFromJSON,
    MarketIndexesMetaFromJSONTyped,
    MarketIndexesMetaToJSON,
    MarketIndexesMetaToJSONTyped,
} from './MarketIndexesMeta';
import type { MarketIndexesData } from './MarketIndexesData';
import {
    MarketIndexesDataFromJSON,
    MarketIndexesDataFromJSONTyped,
    MarketIndexesDataToJSON,
    MarketIndexesDataToJSONTyped,
} from './MarketIndexesData';

/**
 * Response envelope for /v1/market/indexes.
 * @export
 * @interface MarketIndexesResponse
 */
export interface MarketIndexesResponse {
    /**
     * Response metadata for this payload.
     * @type {MarketIndexesMeta}
     * @memberof MarketIndexesResponse
     */
    meta: MarketIndexesMeta;
    /**
     * Primary data payload for this response.
     * @type {MarketIndexesData}
     * @memberof MarketIndexesResponse
     */
    data: MarketIndexesData;
}

/**
 * Check if a given object implements the MarketIndexesResponse interface.
 */
export function instanceOfMarketIndexesResponse(value: object): value is MarketIndexesResponse {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MarketIndexesResponseFromJSON(json: any): MarketIndexesResponse {
    return MarketIndexesResponseFromJSONTyped(json, false);
}

export function MarketIndexesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketIndexesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': MarketIndexesMetaFromJSON(json['meta']),
        'data': MarketIndexesDataFromJSON(json['data']),
    };
}

export function MarketIndexesResponseToJSON(json: any): MarketIndexesResponse {
    return MarketIndexesResponseToJSONTyped(json, false);
}

export function MarketIndexesResponseToJSONTyped(value?: MarketIndexesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MarketIndexesMetaToJSON(value['meta']),
        'data': MarketIndexesDataToJSON(value['data']),
    };
}

