/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketItemAnalyticsCoverage } from './MarketItemAnalyticsCoverage';
import {
    MarketItemAnalyticsCoverageFromJSON,
    MarketItemAnalyticsCoverageFromJSONTyped,
    MarketItemAnalyticsCoverageToJSON,
    MarketItemAnalyticsCoverageToJSONTyped,
} from './MarketItemAnalyticsCoverage';
import type { MarketItemAnalyticsSummary } from './MarketItemAnalyticsSummary';
import {
    MarketItemAnalyticsSummaryFromJSON,
    MarketItemAnalyticsSummaryFromJSONTyped,
    MarketItemAnalyticsSummaryToJSON,
    MarketItemAnalyticsSummaryToJSONTyped,
} from './MarketItemAnalyticsSummary';
import type { MarketItemAnalyticsProvider } from './MarketItemAnalyticsProvider';
import {
    MarketItemAnalyticsProviderFromJSON,
    MarketItemAnalyticsProviderFromJSONTyped,
    MarketItemAnalyticsProviderToJSON,
    MarketItemAnalyticsProviderToJSONTyped,
} from './MarketItemAnalyticsProvider';

/**
 * Payload for /v1/market/items/{item_id}.
 * @export
 * @interface MarketItemAnalyticsData
 */
export interface MarketItemAnalyticsData {
    /**
     * Normalized catalog item ID used by this API.
     * @type {number}
     * @memberof MarketItemAnalyticsData
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof MarketItemAnalyticsData
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof MarketItemAnalyticsData
     */
    phase?: string | null;
    /**
     * Summary value.
     * @type {MarketItemAnalyticsSummary}
     * @memberof MarketItemAnalyticsData
     */
    summary: MarketItemAnalyticsSummary;
    /**
     * Providers value.
     * @type {Array<MarketItemAnalyticsProvider>}
     * @memberof MarketItemAnalyticsData
     */
    providers: Array<MarketItemAnalyticsProvider>;
    /**
     * Coverage value.
     * @type {MarketItemAnalyticsCoverage}
     * @memberof MarketItemAnalyticsData
     */
    coverage: MarketItemAnalyticsCoverage;
}

/**
 * Check if a given object implements the MarketItemAnalyticsData interface.
 */
export function instanceOfMarketItemAnalyticsData(value: object): value is MarketItemAnalyticsData {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('providers' in value) || value['providers'] === undefined) return false;
    if (!('coverage' in value) || value['coverage'] === undefined) return false;
    return true;
}

export function MarketItemAnalyticsDataFromJSON(json: any): MarketItemAnalyticsData {
    return MarketItemAnalyticsDataFromJSONTyped(json, false);
}

export function MarketItemAnalyticsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketItemAnalyticsData {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'summary': MarketItemAnalyticsSummaryFromJSON(json['summary']),
        'providers': ((json['providers'] as Array<any>).map(MarketItemAnalyticsProviderFromJSON)),
        'coverage': MarketItemAnalyticsCoverageFromJSON(json['coverage']),
    };
}

export function MarketItemAnalyticsDataToJSON(json: any): MarketItemAnalyticsData {
    return MarketItemAnalyticsDataToJSONTyped(json, false);
}

export function MarketItemAnalyticsDataToJSONTyped(value?: MarketItemAnalyticsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'summary': MarketItemAnalyticsSummaryToJSON(value['summary']),
        'providers': ((value['providers'] as Array<any>).map(MarketItemAnalyticsProviderToJSON)),
        'coverage': MarketItemAnalyticsCoverageToJSON(value['coverage']),
    };
}

