/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Effective time window used for the analytics query.
 * @export
 * @interface MarketTimeWindowMeta
 */
export interface MarketTimeWindowMeta {
    /**
     * Type of time window selection used for this query.
     * @type {MarketTimeWindowMetaWindowKindEnum}
     * @memberof MarketTimeWindowMeta
     */
    windowKind: MarketTimeWindowMetaWindowKindEnum;
    /**
     * 
     * @type {string}
     * @memberof MarketTimeWindowMeta
     */
    timeframe?: string | null;
    /**
     * Inclusive start timestamp of the effective analytics window (UTC).
     * @type {Date}
     * @memberof MarketTimeWindowMeta
     */
    startAt: Date;
    /**
     * Exclusive end timestamp of the effective analytics window (UTC).
     * @type {Date}
     * @memberof MarketTimeWindowMeta
     */
    endAt: Date;
}


/**
 * @export
 */
export const MarketTimeWindowMetaWindowKindEnum = {
    Preset: 'preset',
    Range: 'range'
} as const;
export type MarketTimeWindowMetaWindowKindEnum = typeof MarketTimeWindowMetaWindowKindEnum[keyof typeof MarketTimeWindowMetaWindowKindEnum];


/**
 * Check if a given object implements the MarketTimeWindowMeta interface.
 */
export function instanceOfMarketTimeWindowMeta(value: object): value is MarketTimeWindowMeta {
    if (!('windowKind' in value) || value['windowKind'] === undefined) return false;
    if (!('startAt' in value) || value['startAt'] === undefined) return false;
    if (!('endAt' in value) || value['endAt'] === undefined) return false;
    return true;
}

export function MarketTimeWindowMetaFromJSON(json: any): MarketTimeWindowMeta {
    return MarketTimeWindowMetaFromJSONTyped(json, false);
}

export function MarketTimeWindowMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketTimeWindowMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'windowKind': json['window_kind'],
        'timeframe': json['timeframe'] == null ? undefined : json['timeframe'],
        'startAt': (new Date(json['start_at'])),
        'endAt': (new Date(json['end_at'])),
    };
}

export function MarketTimeWindowMetaToJSON(json: any): MarketTimeWindowMeta {
    return MarketTimeWindowMetaToJSONTyped(json, false);
}

export function MarketTimeWindowMetaToJSONTyped(value?: MarketTimeWindowMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'window_kind': value['windowKind'],
        'timeframe': value['timeframe'],
        'start_at': value['startAt'].toISOString(),
        'end_at': value['endAt'].toISOString(),
    };
}

