/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { MarketIndicatorsScreenerItem } from './MarketIndicatorsScreenerItem';
import {
    MarketIndicatorsScreenerItemFromJSON,
    MarketIndicatorsScreenerItemFromJSONTyped,
    MarketIndicatorsScreenerItemToJSON,
    MarketIndicatorsScreenerItemToJSONTyped,
} from './MarketIndicatorsScreenerItem';
import type { MarketIndicatorsMeta } from './MarketIndicatorsMeta';
import {
    MarketIndicatorsMetaFromJSON,
    MarketIndicatorsMetaFromJSONTyped,
    MarketIndicatorsMetaToJSON,
    MarketIndicatorsMetaToJSONTyped,
} from './MarketIndicatorsMeta';

/**
 * Response envelope for /v1/market/indicators (bulk screener mode).
 * @export
 * @interface MarketIndicatorsScreenerResponse
 */
export interface MarketIndicatorsScreenerResponse {
    /**
     * Response metadata for this payload.
     * @type {MarketIndicatorsMeta}
     * @memberof MarketIndicatorsScreenerResponse
     */
    meta: MarketIndicatorsMeta;
    /**
     * Primary data payload for this response.
     * @type {Array<MarketIndicatorsScreenerItem>}
     * @memberof MarketIndicatorsScreenerResponse
     */
    data: Array<MarketIndicatorsScreenerItem>;
    /**
     * Pagination metadata for this response.
     * @type {PaginationMeta}
     * @memberof MarketIndicatorsScreenerResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the MarketIndicatorsScreenerResponse interface.
 */
export function instanceOfMarketIndicatorsScreenerResponse(value: object): value is MarketIndicatorsScreenerResponse {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function MarketIndicatorsScreenerResponseFromJSON(json: any): MarketIndicatorsScreenerResponse {
    return MarketIndicatorsScreenerResponseFromJSONTyped(json, false);
}

export function MarketIndicatorsScreenerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketIndicatorsScreenerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': MarketIndicatorsMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(MarketIndicatorsScreenerItemFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function MarketIndicatorsScreenerResponseToJSON(json: any): MarketIndicatorsScreenerResponse {
    return MarketIndicatorsScreenerResponseToJSONTyped(json, false);
}

export function MarketIndicatorsScreenerResponseToJSONTyped(value?: MarketIndicatorsScreenerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MarketIndicatorsMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(MarketIndicatorsScreenerItemToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

