/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An item's price data from a specific provider.
 * @export
 * @interface MarketItem
 */
export interface MarketItem {
    /**
     * Provider key used by this API.
     * @type {string}
     * @memberof MarketItem
     */
    provider: string;
    /**
     * Normalized catalog item ID used by this API.
     * @type {number}
     * @memberof MarketItem
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof MarketItem
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof MarketItem
     */
    phase?: string | null;
    /**
     * Money amount in minor units of the response currency (for example USD cents when currency=USD). Divide by 100 for display.
     * @type {number}
     * @memberof MarketItem
     */
    lowestAsk: number;
    /**
     * Quantity count for this record.
     * @type {number}
     * @memberof MarketItem
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof MarketItem
     */
    link?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarketItem
     */
    url?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MarketItem
     */
    timestamp?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof MarketItem
     */
    lastUpdated?: Date | null;
}

/**
 * Check if a given object implements the MarketItem interface.
 */
export function instanceOfMarketItem(value: object): value is MarketItem {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('lowestAsk' in value) || value['lowestAsk'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function MarketItemFromJSON(json: any): MarketItem {
    return MarketItemFromJSONTyped(json, false);
}

export function MarketItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketItem {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'lowestAsk': json['lowest_ask'],
        'quantity': json['quantity'],
        'link': json['link'] == null ? undefined : json['link'],
        'url': json['url'] == null ? undefined : json['url'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
    };
}

export function MarketItemToJSON(json: any): MarketItem {
    return MarketItemToJSONTyped(json, false);
}

export function MarketItemToJSONTyped(value?: MarketItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'lowest_ask': value['lowestAsk'],
        'quantity': value['quantity'],
        'link': value['link'],
        'url': value['url'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'last_updated': value['lastUpdated'] == null ? value['lastUpdated'] : value['lastUpdated'].toISOString(),
    };
}

