/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for `/v1/items/market-ids` containing provider-specific IDs for all items.
 * @export
 * @interface MarketIdsResponse
 */
export interface MarketIdsResponse {
    /**
     * Mapping of market_hash_name to provider-specific IDs. Each value is a dict of provider ID keys (e.g. `buff163_goods_id`, `csfloat_id`, `steam_nameid`) to their corresponding ID values.
     * @type {{ [key: string]: { [key: string]: any; }; }}
     * @memberof MarketIdsResponse
     */
    items: { [key: string]: { [key: string]: any; }; };
}

/**
 * Check if a given object implements the MarketIdsResponse interface.
 */
export function instanceOfMarketIdsResponse(value: object): value is MarketIdsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function MarketIdsResponseFromJSON(json: any): MarketIdsResponse {
    return MarketIdsResponseFromJSONTyped(json, false);
}

export function MarketIdsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketIdsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'],
    };
}

export function MarketIdsResponseToJSON(json: any): MarketIdsResponse {
    return MarketIdsResponseToJSONTyped(json, false);
}

export function MarketIdsResponseToJSONTyped(value?: MarketIdsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'],
    };
}

