/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Volatility ranking payload.
 * @export
 * @interface MarketRankingVolatilityItem
 */
export interface MarketRankingVolatilityItem {
    /**
     * Normalized catalog item ID used by this API.
     * @type {number}
     * @memberof MarketRankingVolatilityItem
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof MarketRankingVolatilityItem
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof MarketRankingVolatilityItem
     */
    phase?: string | null;
    /**
     * Provider key used by this API.
     * @type {string}
     * @memberof MarketRankingVolatilityItem
     */
    provider: string;
    /**
     * ISO 8601 UTC timestamp when this record was last ingested or processed.
     * @type {Date}
     * @memberof MarketRankingVolatilityItem
     */
    lastUpdated: Date;
    /**
     * Volatility score value.
     * @type {number}
     * @memberof MarketRankingVolatilityItem
     */
    volatilityScore: number;
    /**
     * USD-denominated value for current price.
     * @type {string}
     * @memberof MarketRankingVolatilityItem
     */
    currentPriceUsd: string;
    /**
     * USD-denominated value for min price.
     * @type {string}
     * @memberof MarketRankingVolatilityItem
     */
    minPriceUsd: string;
    /**
     * USD-denominated value for max price.
     * @type {string}
     * @memberof MarketRankingVolatilityItem
     */
    maxPriceUsd: string;
    /**
     * USD-denominated value for std dev.
     * @type {string}
     * @memberof MarketRankingVolatilityItem
     */
    stdDevUsd: string;
    /**
     * Sample count value.
     * @type {number}
     * @memberof MarketRankingVolatilityItem
     */
    sampleCount: number;
}

/**
 * Check if a given object implements the MarketRankingVolatilityItem interface.
 */
export function instanceOfMarketRankingVolatilityItem(value: object): value is MarketRankingVolatilityItem {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    if (!('volatilityScore' in value) || value['volatilityScore'] === undefined) return false;
    if (!('currentPriceUsd' in value) || value['currentPriceUsd'] === undefined) return false;
    if (!('minPriceUsd' in value) || value['minPriceUsd'] === undefined) return false;
    if (!('maxPriceUsd' in value) || value['maxPriceUsd'] === undefined) return false;
    if (!('stdDevUsd' in value) || value['stdDevUsd'] === undefined) return false;
    if (!('sampleCount' in value) || value['sampleCount'] === undefined) return false;
    return true;
}

export function MarketRankingVolatilityItemFromJSON(json: any): MarketRankingVolatilityItem {
    return MarketRankingVolatilityItemFromJSONTyped(json, false);
}

export function MarketRankingVolatilityItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketRankingVolatilityItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'provider': json['provider'],
        'lastUpdated': (new Date(json['last_updated'])),
        'volatilityScore': json['volatility_score'],
        'currentPriceUsd': json['current_price_usd'],
        'minPriceUsd': json['min_price_usd'],
        'maxPriceUsd': json['max_price_usd'],
        'stdDevUsd': json['std_dev_usd'],
        'sampleCount': json['sample_count'],
    };
}

export function MarketRankingVolatilityItemToJSON(json: any): MarketRankingVolatilityItem {
    return MarketRankingVolatilityItemToJSONTyped(json, false);
}

export function MarketRankingVolatilityItemToJSONTyped(value?: MarketRankingVolatilityItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'provider': value['provider'],
        'last_updated': value['lastUpdated'].toISOString(),
        'volatility_score': value['volatilityScore'],
        'current_price_usd': value['currentPriceUsd'],
        'min_price_usd': value['minPriceUsd'],
        'max_price_usd': value['maxPriceUsd'],
        'std_dev_usd': value['stdDevUsd'],
        'sample_count': value['sampleCount'],
    };
}

