/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Doppler and other item phases - single definition.
 * @export
 */
export const PhaseName = {
    Phase1: 'Phase 1',
    Phase2: 'Phase 2',
    Phase3: 'Phase 3',
    Phase4: 'Phase 4',
    Sapphire: 'Sapphire',
    Ruby: 'Ruby',
    BlackPearl: 'Black Pearl',
    Emerald: 'Emerald'
} as const;
export type PhaseName = typeof PhaseName[keyof typeof PhaseName];


export function instanceOfPhaseName(value: any): boolean {
    for (const key in PhaseName) {
        if (Object.prototype.hasOwnProperty.call(PhaseName, key)) {
            if (PhaseName[key as keyof typeof PhaseName] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PhaseNameFromJSON(json: any): PhaseName {
    return PhaseNameFromJSONTyped(json, false);
}

export function PhaseNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhaseName {
    return json as PhaseName;
}

export function PhaseNameToJSON(value?: PhaseName | null): any {
    return value as any;
}

export function PhaseNameToJSONTyped(value: any, ignoreDiscriminator: boolean): PhaseName {
    return value as PhaseName;
}

