/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response metadata for portfolio valuation.
 * @export
 * @interface PortfolioMeta
 */
export interface PortfolioMeta {
    /**
     * Currency code for all money values.
     * @type {string}
     * @memberof PortfolioMeta
     */
    currency: string;
    /**
     * UTC timestamp when this response was generated.
     * @type {Date}
     * @memberof PortfolioMeta
     */
    generatedAt: Date;
    /**
     * Provider keys queried.
     * @type {Array<string>}
     * @memberof PortfolioMeta
     */
    providersQueried: Array<string>;
}

/**
 * Check if a given object implements the PortfolioMeta interface.
 */
export function instanceOfPortfolioMeta(value: object): value is PortfolioMeta {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('providersQueried' in value) || value['providersQueried'] === undefined) return false;
    return true;
}

export function PortfolioMetaFromJSON(json: any): PortfolioMeta {
    return PortfolioMetaFromJSONTyped(json, false);
}

export function PortfolioMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'generatedAt': (new Date(json['generated_at'])),
        'providersQueried': json['providers_queried'],
    };
}

export function PortfolioMetaToJSON(json: any): PortfolioMeta {
    return PortfolioMetaToJSONTyped(json, false);
}

export function PortfolioMetaToJSONTyped(value?: PortfolioMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'generated_at': value['generatedAt'].toISOString(),
        'providers_queried': value['providersQueried'],
    };
}

