/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StickerInfo } from './StickerInfo';
import {
    StickerInfoFromJSON,
    StickerInfoFromJSONTyped,
    StickerInfoToJSON,
    StickerInfoToJSONTyped,
} from './StickerInfo';
import type { CharmInfo } from './CharmInfo';
import {
    CharmInfoFromJSON,
    CharmInfoFromJSONTyped,
    CharmInfoToJSON,
    CharmInfoToJSONTyped,
} from './CharmInfo';

/**
 * A single item entry within a portfolio.
 * @export
 * @interface PortfolioItemOut
 */
export interface PortfolioItemOut {
    /**
     * Entry UUID.
     * @type {string}
     * @memberof PortfolioItemOut
     */
    id: string;
    /**
     * Catalog item ID.
     * @type {number}
     * @memberof PortfolioItemOut
     */
    itemId: number;
    /**
     * Steam market hash name.
     * @type {string}
     * @memberof PortfolioItemOut
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioItemOut
     */
    phase?: string | null;
    /**
     * Number of units held.
     * @type {number}
     * @memberof PortfolioItemOut
     */
    quantity: number;
    /**
     * How the item was added: 'steam' or 'manual'.
     * @type {string}
     * @memberof PortfolioItemOut
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioItemOut
     */
    steamAssetid?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemOut
     */
    floatValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PortfolioItemOut
     */
    paintSeed?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PortfolioItemOut
     */
    inspectLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PortfolioItemOut
     */
    nameTag?: string | null;
    /**
     * 
     * @type {Array<StickerInfo>}
     * @memberof PortfolioItemOut
     */
    stickers?: Array<StickerInfo> | null;
    /**
     * 
     * @type {Array<CharmInfo>}
     * @memberof PortfolioItemOut
     */
    charms?: Array<CharmInfo> | null;
    /**
     * When this entry was added.
     * @type {Date}
     * @memberof PortfolioItemOut
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PortfolioItemOut interface.
 */
export function instanceOfPortfolioItemOut(value: object): value is PortfolioItemOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PortfolioItemOutFromJSON(json: any): PortfolioItemOut {
    return PortfolioItemOutFromJSONTyped(json, false);
}

export function PortfolioItemOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioItemOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'quantity': json['quantity'],
        'source': json['source'],
        'steamAssetid': json['steam_assetid'] == null ? undefined : json['steam_assetid'],
        'floatValue': json['float_value'] == null ? undefined : json['float_value'],
        'paintSeed': json['paint_seed'] == null ? undefined : json['paint_seed'],
        'inspectLink': json['inspect_link'] == null ? undefined : json['inspect_link'],
        'nameTag': json['name_tag'] == null ? undefined : json['name_tag'],
        'stickers': json['stickers'] == null ? undefined : ((json['stickers'] as Array<any>).map(StickerInfoFromJSON)),
        'charms': json['charms'] == null ? undefined : ((json['charms'] as Array<any>).map(CharmInfoFromJSON)),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function PortfolioItemOutToJSON(json: any): PortfolioItemOut {
    return PortfolioItemOutToJSONTyped(json, false);
}

export function PortfolioItemOutToJSONTyped(value?: PortfolioItemOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'quantity': value['quantity'],
        'source': value['source'],
        'steam_assetid': value['steamAssetid'],
        'float_value': value['floatValue'],
        'paint_seed': value['paintSeed'],
        'inspect_link': value['inspectLink'],
        'name_tag': value['nameTag'],
        'stickers': value['stickers'] == null ? undefined : ((value['stickers'] as Array<any>).map(StickerInfoToJSON)),
        'charms': value['charms'] == null ? undefined : ((value['charms'] as Array<any>).map(CharmInfoToJSON)),
        'created_at': value['createdAt'].toISOString(),
    };
}

