/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata for saved-portfolio historical valuation.
 * @export
 * @interface PortfolioHistoryMeta
 */
export interface PortfolioHistoryMeta {
    /**
     * Portfolio UUID.
     * @type {string}
     * @memberof PortfolioHistoryMeta
     */
    portfolioId: string;
    /**
     * Currency code for all money values.
     * @type {string}
     * @memberof PortfolioHistoryMeta
     */
    currency: string;
    /**
     * Provider keys queried.
     * @type {Array<string>}
     * @memberof PortfolioHistoryMeta
     */
    providersQueried: Array<string>;
    /**
     * Inclusive UTC start date for the requested window.
     * @type {Date}
     * @memberof PortfolioHistoryMeta
     */
    startDate: Date;
    /**
     * Inclusive UTC end date for the requested window.
     * @type {Date}
     * @memberof PortfolioHistoryMeta
     */
    endDate: Date;
    /**
     * History interval. Always `1d`.
     * @type {PortfolioHistoryMetaIntervalEnum}
     * @memberof PortfolioHistoryMeta
     */
    interval?: PortfolioHistoryMetaIntervalEnum;
    /**
     * Holdings replay basis. Always `ledger_close`.
     * @type {PortfolioHistoryMetaHoldingsBasisEnum}
     * @memberof PortfolioHistoryMeta
     */
    holdingsBasis?: PortfolioHistoryMetaHoldingsBasisEnum;
    /**
     * Valuation basis. Always `best_provider_close`.
     * @type {PortfolioHistoryMetaValuationBasisEnum}
     * @memberof PortfolioHistoryMeta
     */
    valuationBasis?: PortfolioHistoryMetaValuationBasisEnum;
}


/**
 * @export
 */
export const PortfolioHistoryMetaIntervalEnum = {
    _1d: '1d'
} as const;
export type PortfolioHistoryMetaIntervalEnum = typeof PortfolioHistoryMetaIntervalEnum[keyof typeof PortfolioHistoryMetaIntervalEnum];

/**
 * @export
 */
export const PortfolioHistoryMetaHoldingsBasisEnum = {
    LedgerClose: 'ledger_close'
} as const;
export type PortfolioHistoryMetaHoldingsBasisEnum = typeof PortfolioHistoryMetaHoldingsBasisEnum[keyof typeof PortfolioHistoryMetaHoldingsBasisEnum];

/**
 * @export
 */
export const PortfolioHistoryMetaValuationBasisEnum = {
    BestProviderClose: 'best_provider_close'
} as const;
export type PortfolioHistoryMetaValuationBasisEnum = typeof PortfolioHistoryMetaValuationBasisEnum[keyof typeof PortfolioHistoryMetaValuationBasisEnum];


/**
 * Check if a given object implements the PortfolioHistoryMeta interface.
 */
export function instanceOfPortfolioHistoryMeta(value: object): value is PortfolioHistoryMeta {
    if (!('portfolioId' in value) || value['portfolioId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('providersQueried' in value) || value['providersQueried'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function PortfolioHistoryMetaFromJSON(json: any): PortfolioHistoryMeta {
    return PortfolioHistoryMetaFromJSONTyped(json, false);
}

export function PortfolioHistoryMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioHistoryMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'portfolioId': json['portfolio_id'],
        'currency': json['currency'],
        'providersQueried': json['providers_queried'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'interval': json['interval'] == null ? undefined : json['interval'],
        'holdingsBasis': json['holdings_basis'] == null ? undefined : json['holdings_basis'],
        'valuationBasis': json['valuation_basis'] == null ? undefined : json['valuation_basis'],
    };
}

export function PortfolioHistoryMetaToJSON(json: any): PortfolioHistoryMeta {
    return PortfolioHistoryMetaToJSONTyped(json, false);
}

export function PortfolioHistoryMetaToJSONTyped(value?: PortfolioHistoryMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portfolio_id': value['portfolioId'],
        'currency': value['currency'],
        'providers_queried': value['providersQueried'],
        'start_date': value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'].toISOString().substring(0,10),
        'interval': value['interval'],
        'holdings_basis': value['holdingsBasis'],
        'valuation_basis': value['valuationBasis'],
    };
}

