/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortfolioHistoryMeta } from './PortfolioHistoryMeta';
import {
    PortfolioHistoryMetaFromJSON,
    PortfolioHistoryMetaFromJSONTyped,
    PortfolioHistoryMetaToJSON,
    PortfolioHistoryMetaToJSONTyped,
} from './PortfolioHistoryMeta';
import type { CursorPaginationMeta } from './CursorPaginationMeta';
import {
    CursorPaginationMetaFromJSON,
    CursorPaginationMetaFromJSONTyped,
    CursorPaginationMetaToJSON,
    CursorPaginationMetaToJSONTyped,
} from './CursorPaginationMeta';
import type { PortfolioHistoryPoint } from './PortfolioHistoryPoint';
import {
    PortfolioHistoryPointFromJSON,
    PortfolioHistoryPointFromJSONTyped,
    PortfolioHistoryPointToJSON,
    PortfolioHistoryPointToJSONTyped,
} from './PortfolioHistoryPoint';

/**
 * Response envelope for GET /v1/portfolio/{portfolio_id}/history.
 * @export
 * @interface PortfolioHistoryPage
 */
export interface PortfolioHistoryPage {
    /**
     * Response metadata.
     * @type {PortfolioHistoryMeta}
     * @memberof PortfolioHistoryPage
     */
    meta: PortfolioHistoryMeta;
    /**
     * Ordered daily valuation points.
     * @type {Array<PortfolioHistoryPoint>}
     * @memberof PortfolioHistoryPage
     */
    data: Array<PortfolioHistoryPoint>;
    /**
     * Cursor pagination metadata.
     * @type {CursorPaginationMeta}
     * @memberof PortfolioHistoryPage
     */
    pagination: CursorPaginationMeta;
}

/**
 * Check if a given object implements the PortfolioHistoryPage interface.
 */
export function instanceOfPortfolioHistoryPage(value: object): value is PortfolioHistoryPage {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PortfolioHistoryPageFromJSON(json: any): PortfolioHistoryPage {
    return PortfolioHistoryPageFromJSONTyped(json, false);
}

export function PortfolioHistoryPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioHistoryPage {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': PortfolioHistoryMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(PortfolioHistoryPointFromJSON)),
        'pagination': CursorPaginationMetaFromJSON(json['pagination']),
    };
}

export function PortfolioHistoryPageToJSON(json: any): PortfolioHistoryPage {
    return PortfolioHistoryPageToJSONTyped(json, false);
}

export function PortfolioHistoryPageToJSONTyped(value?: PortfolioHistoryPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PortfolioHistoryMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(PortfolioHistoryPointToJSON)),
        'pagination': CursorPaginationMetaToJSON(value['pagination']),
    };
}

