/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchPriceQuote } from './BatchPriceQuote';
import {
    BatchPriceQuoteFromJSON,
    BatchPriceQuoteFromJSONTyped,
    BatchPriceQuoteToJSON,
    BatchPriceQuoteToJSONTyped,
} from './BatchPriceQuote';

/**
 * Valuation line item for one portfolio entry.
 * @export
 * @interface PortfolioLineItem
 */
export interface PortfolioLineItem {
    /**
     * Normalized catalog item ID used by this API.
     * @type {number}
     * @memberof PortfolioLineItem
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof PortfolioLineItem
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioLineItem
     */
    phase?: string | null;
    /**
     * Number of units held.
     * @type {number}
     * @memberof PortfolioLineItem
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioLineItem
     */
    bestAsk?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PortfolioLineItem
     */
    bestBid?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PortfolioLineItem
     */
    itemValue?: number | null;
    /**
     * Per-provider price quotes.
     * @type {Array<BatchPriceQuote>}
     * @memberof PortfolioLineItem
     */
    providers?: Array<BatchPriceQuote>;
}

/**
 * Check if a given object implements the PortfolioLineItem interface.
 */
export function instanceOfPortfolioLineItem(value: object): value is PortfolioLineItem {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function PortfolioLineItemFromJSON(json: any): PortfolioLineItem {
    return PortfolioLineItemFromJSONTyped(json, false);
}

export function PortfolioLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioLineItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'quantity': json['quantity'],
        'bestAsk': json['best_ask'] == null ? undefined : json['best_ask'],
        'bestBid': json['best_bid'] == null ? undefined : json['best_bid'],
        'itemValue': json['item_value'] == null ? undefined : json['item_value'],
        'providers': json['providers'] == null ? undefined : ((json['providers'] as Array<any>).map(BatchPriceQuoteFromJSON)),
    };
}

export function PortfolioLineItemToJSON(json: any): PortfolioLineItem {
    return PortfolioLineItemToJSONTyped(json, false);
}

export function PortfolioLineItemToJSONTyped(value?: PortfolioLineItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'quantity': value['quantity'],
        'best_ask': value['bestAsk'],
        'best_bid': value['bestBid'],
        'item_value': value['itemValue'],
        'providers': value['providers'] == null ? undefined : ((value['providers'] as Array<any>).map(BatchPriceQuoteToJSON)),
    };
}

