/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Filter metadata for prices endpoint.
 * @export
 * @interface PricesFilterMeta
 */
export interface PricesFilterMeta {
    /**
     * 
     * @type {string}
     * @memberof PricesFilterMeta
     */
    marketHashName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PricesFilterMeta
     */
    phase?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PricesFilterMeta
     */
    requestedProviders?: Array<string> | null;
}

/**
 * Check if a given object implements the PricesFilterMeta interface.
 */
export function instanceOfPricesFilterMeta(value: object): value is PricesFilterMeta {
    return true;
}

export function PricesFilterMetaFromJSON(json: any): PricesFilterMeta {
    return PricesFilterMetaFromJSONTyped(json, false);
}

export function PricesFilterMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricesFilterMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'marketHashName': json['market_hash_name'] == null ? undefined : json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'requestedProviders': json['requested_providers'] == null ? undefined : json['requested_providers'],
    };
}

export function PricesFilterMetaToJSON(json: any): PricesFilterMeta {
    return PricesFilterMetaToJSONTyped(json, false);
}

export function PricesFilterMetaToJSONTyped(value?: PricesFilterMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'requested_providers': value['requestedProviders'],
    };
}

