/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceCandlesMeta } from './PriceCandlesMeta';
import {
    PriceCandlesMetaFromJSON,
    PriceCandlesMetaFromJSONTyped,
    PriceCandlesMetaToJSON,
    PriceCandlesMetaToJSONTyped,
} from './PriceCandlesMeta';
import type { CursorPaginationMeta } from './CursorPaginationMeta';
import {
    CursorPaginationMetaFromJSON,
    CursorPaginationMetaFromJSONTyped,
    CursorPaginationMetaToJSON,
    CursorPaginationMetaToJSONTyped,
} from './CursorPaginationMeta';
import type { PriceCandleItem } from './PriceCandleItem';
import {
    PriceCandleItemFromJSON,
    PriceCandleItemFromJSONTyped,
    PriceCandleItemToJSON,
    PriceCandleItemToJSONTyped,
} from './PriceCandleItem';

/**
 * Paginated candle response with cursor-based pagination.
 * @export
 * @interface PriceCandlesPage
 */
export interface PriceCandlesPage {
    /**
     * Response metadata for this payload.
     * @type {PriceCandlesMeta}
     * @memberof PriceCandlesPage
     */
    meta: PriceCandlesMeta;
    /**
     * Primary data payload for this response.
     * @type {Array<PriceCandleItem>}
     * @memberof PriceCandlesPage
     */
    data: Array<PriceCandleItem>;
    /**
     * Pagination metadata for this response.
     * @type {CursorPaginationMeta}
     * @memberof PriceCandlesPage
     */
    pagination: CursorPaginationMeta;
}

/**
 * Check if a given object implements the PriceCandlesPage interface.
 */
export function instanceOfPriceCandlesPage(value: object): value is PriceCandlesPage {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PriceCandlesPageFromJSON(json: any): PriceCandlesPage {
    return PriceCandlesPageFromJSONTyped(json, false);
}

export function PriceCandlesPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceCandlesPage {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': PriceCandlesMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(PriceCandleItemFromJSON)),
        'pagination': CursorPaginationMetaFromJSON(json['pagination']),
    };
}

export function PriceCandlesPageToJSON(json: any): PriceCandlesPage {
    return PriceCandlesPageToJSONTyped(json, false);
}

export function PriceCandlesPageToJSONTyped(value?: PriceCandlesPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PriceCandlesMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(PriceCandleItemToJSON)),
        'pagination': CursorPaginationMetaToJSON(value['pagination']),
    };
}

