/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single price snapshot at a point in time.
 * @export
 * @interface PriceSnapshot
 */
export interface PriceSnapshot {
    /**
     * Normalized catalog item ID used by this API.
     * @type {number}
     * @memberof PriceSnapshot
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof PriceSnapshot
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof PriceSnapshot
     */
    phase?: string | null;
    /**
     * Provider key used by this API.
     * @type {string}
     * @memberof PriceSnapshot
     */
    provider: string;
    /**
     * Time value.
     * @type {Date}
     * @memberof PriceSnapshot
     */
    time: Date;
    /**
     * Money amount in minor units of the response currency (for example USD cents when currency=USD). Divide by 100 for display.
     * @type {number}
     * @memberof PriceSnapshot
     */
    price: number;
    /**
     * ISO 4217 currency code for the value context.
     * @type {string}
     * @memberof PriceSnapshot
     */
    currency: string;
    /**
     * Quantity value.
     * @type {number}
     * @memberof PriceSnapshot
     */
    quantity: number;
}

/**
 * Check if a given object implements the PriceSnapshot interface.
 */
export function instanceOfPriceSnapshot(value: object): value is PriceSnapshot {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function PriceSnapshotFromJSON(json: any): PriceSnapshot {
    return PriceSnapshotFromJSONTyped(json, false);
}

export function PriceSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceSnapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'provider': json['provider'],
        'time': (new Date(json['time'])),
        'price': json['price'],
        'currency': json['currency'],
        'quantity': json['quantity'],
    };
}

export function PriceSnapshotToJSON(json: any): PriceSnapshot {
    return PriceSnapshotToJSONTyped(json, false);
}

export function PriceSnapshotToJSONTyped(value?: PriceSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'provider': value['provider'],
        'time': value['time'].toISOString(),
        'price': value['price'],
        'currency': value['currency'],
        'quantity': value['quantity'],
    };
}

