/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PricesFilterMeta } from './PricesFilterMeta';
import {
    PricesFilterMetaFromJSON,
    PricesFilterMetaFromJSONTyped,
    PricesFilterMetaToJSON,
    PricesFilterMetaToJSONTyped,
} from './PricesFilterMeta';

/**
 * Metadata for prices response.
 * @export
 * @interface PricesMeta
 */
export interface PricesMeta {
    /**
     * ISO 4217 currency code for the value context.
     * @type {string}
     * @memberof PricesMeta
     */
    currency: string;
    /**
     * Effective request filters applied to this response.
     * @type {PricesFilterMeta}
     * @memberof PricesMeta
     */
    filters: PricesFilterMeta;
    /**
     * Provider keys that returned data in this response.
     * @type {Array<string>}
     * @memberof PricesMeta
     */
    returnedProviders: Array<string>;
}

/**
 * Check if a given object implements the PricesMeta interface.
 */
export function instanceOfPricesMeta(value: object): value is PricesMeta {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('filters' in value) || value['filters'] === undefined) return false;
    if (!('returnedProviders' in value) || value['returnedProviders'] === undefined) return false;
    return true;
}

export function PricesMetaFromJSON(json: any): PricesMeta {
    return PricesMetaFromJSONTyped(json, false);
}

export function PricesMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricesMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'filters': PricesFilterMetaFromJSON(json['filters']),
        'returnedProviders': json['returned_providers'],
    };
}

export function PricesMetaToJSON(json: any): PricesMeta {
    return PricesMetaToJSONTyped(json, false);
}

export function PricesMetaToJSONTyped(value?: PricesMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'filters': PricesFilterMetaToJSON(value['filters']),
        'returned_providers': value['returnedProviders'],
    };
}

