/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { MarketItem } from './MarketItem';
import {
    MarketItemFromJSON,
    MarketItemFromJSONTyped,
    MarketItemToJSON,
    MarketItemToJSONTyped,
} from './MarketItem';
import type { PricesMeta } from './PricesMeta';
import {
    PricesMetaFromJSON,
    PricesMetaFromJSONTyped,
    PricesMetaToJSON,
    PricesMetaToJSONTyped,
} from './PricesMeta';

/**
 * 
 * @export
 * @interface PricesPaginatedResponseMarketItem
 */
export interface PricesPaginatedResponseMarketItem {
    /**
     * Response metadata for this payload.
     * @type {PricesMeta}
     * @memberof PricesPaginatedResponseMarketItem
     */
    meta: PricesMeta;
    /**
     * List of returned items.
     * @type {Array<MarketItem>}
     * @memberof PricesPaginatedResponseMarketItem
     */
    items: Array<MarketItem>;
    /**
     * Pagination metadata for this response.
     * @type {PaginationMeta}
     * @memberof PricesPaginatedResponseMarketItem
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PricesPaginatedResponseMarketItem interface.
 */
export function instanceOfPricesPaginatedResponseMarketItem(value: object): value is PricesPaginatedResponseMarketItem {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PricesPaginatedResponseMarketItemFromJSON(json: any): PricesPaginatedResponseMarketItem {
    return PricesPaginatedResponseMarketItemFromJSONTyped(json, false);
}

export function PricesPaginatedResponseMarketItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricesPaginatedResponseMarketItem {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': PricesMetaFromJSON(json['meta']),
        'items': ((json['items'] as Array<any>).map(MarketItemFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PricesPaginatedResponseMarketItemToJSON(json: any): PricesPaginatedResponseMarketItem {
    return PricesPaginatedResponseMarketItemToJSONTyped(json, false);
}

export function PricesPaginatedResponseMarketItemToJSONTyped(value?: PricesPaginatedResponseMarketItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PricesMetaToJSON(value['meta']),
        'items': ((value['items'] as Array<any>).map(MarketItemToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

