/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata for candles response (constant across all items).
 * @export
 * @interface PriceCandlesMeta
 */
export interface PriceCandlesMeta {
    /**
     * Normalized catalog item ID used by this API.
     * @type {number}
     * @memberof PriceCandlesMeta
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof PriceCandlesMeta
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof PriceCandlesMeta
     */
    phase?: string | null;
    /**
     * Composite provider scope for this response.
     * @type {string}
     * @memberof PriceCandlesMeta
     */
    provider?: string;
    /**
     * ISO 4217 currency code for the value context.
     * @type {string}
     * @memberof PriceCandlesMeta
     */
    currency: string;
    /**
     * Time bucket interval used for aggregation.
     * @type {string}
     * @memberof PriceCandlesMeta
     */
    interval: string;
    /**
     * Inclusive start timestamp for the requested window (UTC).
     * @type {Date}
     * @memberof PriceCandlesMeta
     */
    start: Date;
    /**
     * Exclusive end timestamp for the requested window (UTC).
     * @type {Date}
     * @memberof PriceCandlesMeta
     */
    end: Date;
}

/**
 * Check if a given object implements the PriceCandlesMeta interface.
 */
export function instanceOfPriceCandlesMeta(value: object): value is PriceCandlesMeta {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function PriceCandlesMetaFromJSON(json: any): PriceCandlesMeta {
    return PriceCandlesMetaFromJSONTyped(json, false);
}

export function PriceCandlesMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceCandlesMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'currency': json['currency'],
        'interval': json['interval'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
    };
}

export function PriceCandlesMetaToJSON(json: any): PriceCandlesMeta {
    return PriceCandlesMetaToJSONTyped(json, false);
}

export function PriceCandlesMetaToJSONTyped(value?: PriceCandlesMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'provider': value['provider'],
        'currency': value['currency'],
        'interval': value['interval'],
        'start': value['start'].toISOString(),
        'end': value['end'].toISOString(),
    };
}

