/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Provider provenance for composite candle extremes.
 * @export
 * @interface Providers
 */
export interface Providers {
    /**
     * Provider key that contributed the returned high value.
     * @type {string}
     * @memberof Providers
     */
    h: string;
    /**
     * Provider key that contributed the returned low value.
     * @type {string}
     * @memberof Providers
     */
    l: string;
}

/**
 * Check if a given object implements the Providers interface.
 */
export function instanceOfProviders(value: object): value is Providers {
    if (!('h' in value) || value['h'] === undefined) return false;
    if (!('l' in value) || value['l'] === undefined) return false;
    return true;
}

export function ProvidersFromJSON(json: any): Providers {
    return ProvidersFromJSONTyped(json, false);
}

export function ProvidersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Providers {
    if (json == null) {
        return json;
    }
    return {
        
        'h': json['h'],
        'l': json['l'],
    };
}

export function ProvidersToJSON(json: any): Providers {
    return ProvidersToJSONTyped(json, false);
}

export function ProvidersToJSONTyped(value?: Providers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'h': value['h'],
        'l': value['l'],
    };
}

