/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProviderFees } from './ProviderFees';
import {
    ProviderFeesFromJSON,
    ProviderFeesFromJSONTyped,
    ProviderFeesToJSON,
    ProviderFeesToJSONTyped,
} from './ProviderFees';
import type { ProviderHealth } from './ProviderHealth';
import {
    ProviderHealthFromJSON,
    ProviderHealthFromJSONTyped,
    ProviderHealthToJSON,
    ProviderHealthToJSONTyped,
} from './ProviderHealth';
import type { ProviderFeatures } from './ProviderFeatures';
import {
    ProviderFeaturesFromJSON,
    ProviderFeaturesFromJSONTyped,
    ProviderFeaturesToJSON,
    ProviderFeaturesToJSONTyped,
} from './ProviderFeatures';

/**
 * 
 * @export
 * @interface ProviderInfo
 */
export interface ProviderInfo {
    /**
     * Stable provider key used in request and response payloads.
     * @type {string}
     * @memberof ProviderInfo
     */
    key: string;
    /**
     * CDN URL for the provider logo asset.
     * @type {string}
     * @memberof ProviderInfo
     */
    logo: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderInfo
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProviderInfo
     */
    marketType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProviderInfo
     */
    defaultCurrency?: string | null;
    /**
     * Fee configuration values keyed by fee type.
     * @type {ProviderFees}
     * @memberof ProviderInfo
     */
    fees: ProviderFees;
    /**
     * Feature capability flags for this provider.
     * @type {ProviderFeatures}
     * @memberof ProviderInfo
     */
    features: ProviderFeatures;
    /**
     * Provider health metrics and aggregate diagnostics.
     * @type {ProviderHealth}
     * @memberof ProviderInfo
     */
    health: ProviderHealth;
}

/**
 * Check if a given object implements the ProviderInfo interface.
 */
export function instanceOfProviderInfo(value: object): value is ProviderInfo {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('logo' in value) || value['logo'] === undefined) return false;
    if (!('fees' in value) || value['fees'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    if (!('health' in value) || value['health'] === undefined) return false;
    return true;
}

export function ProviderInfoFromJSON(json: any): ProviderInfo {
    return ProviderInfoFromJSONTyped(json, false);
}

export function ProviderInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'logo': json['logo'],
        'code': json['code'] == null ? undefined : json['code'],
        'marketType': json['market_type'] == null ? undefined : json['market_type'],
        'defaultCurrency': json['default_currency'] == null ? undefined : json['default_currency'],
        'fees': ProviderFeesFromJSON(json['fees']),
        'features': ProviderFeaturesFromJSON(json['features']),
        'health': ProviderHealthFromJSON(json['health']),
    };
}

export function ProviderInfoToJSON(json: any): ProviderInfo {
    return ProviderInfoToJSONTyped(json, false);
}

export function ProviderInfoToJSONTyped(value?: ProviderInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'logo': value['logo'],
        'code': value['code'],
        'market_type': value['marketType'],
        'default_currency': value['defaultCurrency'],
        'fees': ProviderFeesToJSON(value['fees']),
        'features': ProviderFeaturesToJSON(value['features']),
        'health': ProviderHealthToJSON(value['health']),
    };
}

