/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderHealth
 */
export interface ProviderHealth {
    /**
     * Health or processing status value.
     * @type {string}
     * @memberof ProviderHealth
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof ProviderHealth
     */
    lastCheckedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ProviderHealth
     */
    totalOffers?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProviderHealth
     */
    uniqueItems?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProviderHealth
     */
    marketCoverage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProviderHealth
     */
    totalValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProviderHealth
     */
    totalValueUsd?: number | null;
}

/**
 * Check if a given object implements the ProviderHealth interface.
 */
export function instanceOfProviderHealth(value: object): value is ProviderHealth {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ProviderHealthFromJSON(json: any): ProviderHealth {
    return ProviderHealthFromJSONTyped(json, false);
}

export function ProviderHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderHealth {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'lastCheckedAt': json['last_checked_at'] == null ? undefined : (new Date(json['last_checked_at'])),
        'totalOffers': json['total_offers'] == null ? undefined : json['total_offers'],
        'uniqueItems': json['unique_items'] == null ? undefined : json['unique_items'],
        'marketCoverage': json['market_coverage'] == null ? undefined : json['market_coverage'],
        'totalValue': json['total_value'] == null ? undefined : json['total_value'],
        'totalValueUsd': json['total_value_usd'] == null ? undefined : json['total_value_usd'],
    };
}

export function ProviderHealthToJSON(json: any): ProviderHealth {
    return ProviderHealthToJSONTyped(json, false);
}

export function ProviderHealthToJSONTyped(value?: ProviderHealth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'last_checked_at': value['lastCheckedAt'] == null ? value['lastCheckedAt'] : value['lastCheckedAt'].toISOString(),
        'total_offers': value['totalOffers'],
        'unique_items': value['uniqueItems'],
        'market_coverage': value['marketCoverage'],
        'total_value': value['totalValue'],
        'total_value_usd': value['totalValueUsd'],
    };
}

