/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single transaction entry within a portfolio.
 * @export
 * @interface TransactionOut
 */
export interface TransactionOut {
    /**
     * Transaction UUID.
     * @type {string}
     * @memberof TransactionOut
     */
    id: string;
    /**
     * Catalog item ID.
     * @type {number}
     * @memberof TransactionOut
     */
    itemId: number;
    /**
     * Steam market hash name.
     * @type {string}
     * @memberof TransactionOut
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionOut
     */
    phase?: string | null;
    /**
     * Transaction type: 'buy' or 'sell'.
     * @type {string}
     * @memberof TransactionOut
     */
    type: string;
    /**
     * Number of units.
     * @type {number}
     * @memberof TransactionOut
     */
    quantity: number;
    /**
     * Per-unit price in minor units.
     * @type {number}
     * @memberof TransactionOut
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionOut
     */
    feeAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionOut
     */
    feePercentage?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionOut
     */
    marketplace?: string | null;
    /**
     * Transaction date.
     * @type {Date}
     * @memberof TransactionOut
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof TransactionOut
     */
    note?: string | null;
    /**
     * Currency code.
     * @type {string}
     * @memberof TransactionOut
     */
    currency: string;
    /**
     * When this transaction was recorded.
     * @type {Date}
     * @memberof TransactionOut
     */
    createdAt: Date;
    /**
     * When this transaction was last modified.
     * @type {Date}
     * @memberof TransactionOut
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the TransactionOut interface.
 */
export function instanceOfTransactionOut(value: object): value is TransactionOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TransactionOutFromJSON(json: any): TransactionOut {
    return TransactionOutFromJSONTyped(json, false);
}

export function TransactionOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'type': json['type'],
        'quantity': json['quantity'],
        'price': json['price'],
        'feeAmount': json['fee_amount'] == null ? undefined : json['fee_amount'],
        'feePercentage': json['fee_percentage'] == null ? undefined : json['fee_percentage'],
        'marketplace': json['marketplace'] == null ? undefined : json['marketplace'],
        'date': (new Date(json['date'])),
        'note': json['note'] == null ? undefined : json['note'],
        'currency': json['currency'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function TransactionOutToJSON(json: any): TransactionOut {
    return TransactionOutToJSONTyped(json, false);
}

export function TransactionOutToJSONTyped(value?: TransactionOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'type': value['type'],
        'quantity': value['quantity'],
        'price': value['price'],
        'fee_amount': value['feeAmount'],
        'fee_percentage': value['feePercentage'],
        'marketplace': value['marketplace'],
        'date': value['date'].toISOString().substring(0,10),
        'note': value['note'],
        'currency': value['currency'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

