/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WatchlistCreateRequest
 */
export interface WatchlistCreateRequest {
    /**
     * Normalized catalog item ID to save to the watchlist.
     * @type {number}
     * @memberof WatchlistCreateRequest
     */
    itemId: number;
}

/**
 * Check if a given object implements the WatchlistCreateRequest interface.
 */
export function instanceOfWatchlistCreateRequest(value: object): value is WatchlistCreateRequest {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    return true;
}

export function WatchlistCreateRequestFromJSON(json: any): WatchlistCreateRequest {
    return WatchlistCreateRequestFromJSONTyped(json, false);
}

export function WatchlistCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchlistCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
    };
}

export function WatchlistCreateRequestToJSON(json: any): WatchlistCreateRequest {
    return WatchlistCreateRequestToJSONTyped(json, false);
}

export function WatchlistCreateRequestToJSONTyped(value?: WatchlistCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
    };
}

