/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { WatchlistItem } from './WatchlistItem';
import {
    WatchlistItemFromJSON,
    WatchlistItemFromJSONTyped,
    WatchlistItemToJSON,
    WatchlistItemToJSONTyped,
} from './WatchlistItem';

/**
 * Paginated watchlist response.
 * @export
 * @interface WatchlistResponse
 */
export interface WatchlistResponse {
    /**
     * Saved watchlist entries.
     * @type {Array<WatchlistItem>}
     * @memberof WatchlistResponse
     */
    items: Array<WatchlistItem>;
    /**
     * Cursor pagination metadata.
     * @type {PaginationMeta}
     * @memberof WatchlistResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the WatchlistResponse interface.
 */
export function instanceOfWatchlistResponse(value: object): value is WatchlistResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function WatchlistResponseFromJSON(json: any): WatchlistResponse {
    return WatchlistResponseFromJSONTyped(json, false);
}

export function WatchlistResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchlistResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WatchlistItemFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function WatchlistResponseToJSON(json: any): WatchlistResponse {
    return WatchlistResponseToJSONTyped(json, false);
}

export function WatchlistResponseToJSONTyped(value?: WatchlistResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WatchlistItemToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

