/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One saved watchlist entry.
 * @export
 * @interface WatchlistItem
 */
export interface WatchlistItem {
    /**
     * Unique identifier for this saved entry.
     * @type {string}
     * @memberof WatchlistItem
     */
    id: string;
    /**
     * Normalized catalog item ID.
     * @type {number}
     * @memberof WatchlistItem
     */
    itemId: number;
    /**
     * Canonical Steam market hash name for the item.
     * @type {string}
     * @memberof WatchlistItem
     */
    marketHashName: string;
    /**
     * 
     * @type {string}
     * @memberof WatchlistItem
     */
    phase?: string | null;
    /**
     * ISO 8601 UTC timestamp when this entry was created.
     * @type {Date}
     * @memberof WatchlistItem
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the WatchlistItem interface.
 */
export function instanceOfWatchlistItem(value: object): value is WatchlistItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function WatchlistItemFromJSON(json: any): WatchlistItem {
    return WatchlistItemFromJSONTyped(json, false);
}

export function WatchlistItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchlistItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function WatchlistItemToJSON(json: any): WatchlistItem {
    return WatchlistItemToJSONTyped(json, false);
}

export function WatchlistItemToJSONTyped(value?: WatchlistItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'created_at': value['createdAt'].toISOString(),
    };
}

