/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Update mutable outbound webhook destination fields.
 * @export
 * @interface WebhookUpdateRequest
 */
export interface WebhookUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof WebhookUpdateRequest
     */
    label?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WebhookUpdateRequest
     */
    url?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookUpdateRequest
     */
    isActive?: boolean | null;
}

/**
 * Check if a given object implements the WebhookUpdateRequest interface.
 */
export function instanceOfWebhookUpdateRequest(value: object): value is WebhookUpdateRequest {
    return true;
}

export function WebhookUpdateRequestFromJSON(json: any): WebhookUpdateRequest {
    return WebhookUpdateRequestFromJSONTyped(json, false);
}

export function WebhookUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'url': json['url'] == null ? undefined : json['url'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function WebhookUpdateRequestToJSON(json: any): WebhookUpdateRequest {
    return WebhookUpdateRequestToJSONTyped(json, false);
}

export function WebhookUpdateRequestToJSONTyped(value?: WebhookUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'url': value['url'],
        'is_active': value['isActive'],
    };
}

