/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One outbound webhook HTTP attempt.
 * @export
 * @interface WebhookDeliveryAttemptSummary
 */
export interface WebhookDeliveryAttemptSummary {
    /**
     * One-based attempt number for this delivery.
     * @type {number}
     * @memberof WebhookDeliveryAttemptSummary
     */
    attemptNumber: number;
    /**
     * Attempt outcome status.
     * @type {string}
     * @memberof WebhookDeliveryAttemptSummary
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof WebhookDeliveryAttemptSummary
     */
    httpStatus?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryAttemptSummary
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryAttemptSummary
     */
    responseBodyExcerpt?: string | null;
    /**
     * ISO 8601 UTC timestamp when this attempt was recorded.
     * @type {Date}
     * @memberof WebhookDeliveryAttemptSummary
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the WebhookDeliveryAttemptSummary interface.
 */
export function instanceOfWebhookDeliveryAttemptSummary(value: object): value is WebhookDeliveryAttemptSummary {
    if (!('attemptNumber' in value) || value['attemptNumber'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function WebhookDeliveryAttemptSummaryFromJSON(json: any): WebhookDeliveryAttemptSummary {
    return WebhookDeliveryAttemptSummaryFromJSONTyped(json, false);
}

export function WebhookDeliveryAttemptSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryAttemptSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'attemptNumber': json['attempt_number'],
        'status': json['status'],
        'httpStatus': json['http_status'] == null ? undefined : json['http_status'],
        'error': json['error'] == null ? undefined : json['error'],
        'responseBodyExcerpt': json['response_body_excerpt'] == null ? undefined : json['response_body_excerpt'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function WebhookDeliveryAttemptSummaryToJSON(json: any): WebhookDeliveryAttemptSummary {
    return WebhookDeliveryAttemptSummaryToJSONTyped(json, false);
}

export function WebhookDeliveryAttemptSummaryToJSONTyped(value?: WebhookDeliveryAttemptSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempt_number': value['attemptNumber'],
        'status': value['status'],
        'http_status': value['httpStatus'],
        'error': value['error'],
        'response_body_excerpt': value['responseBodyExcerpt'],
        'created_at': value['createdAt'].toISOString(),
    };
}

