/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEndpointSummary } from './WebhookEndpointSummary';
import {
    WebhookEndpointSummaryFromJSON,
    WebhookEndpointSummaryFromJSONTyped,
    WebhookEndpointSummaryToJSON,
    WebhookEndpointSummaryToJSONTyped,
} from './WebhookEndpointSummary';

/**
 * List of configured outbound webhook destinations.
 * @export
 * @interface WebhookEndpointsResponse
 */
export interface WebhookEndpointsResponse {
    /**
     * Configured webhook destinations.
     * @type {Array<WebhookEndpointSummary>}
     * @memberof WebhookEndpointsResponse
     */
    webhooks: Array<WebhookEndpointSummary>;
}

/**
 * Check if a given object implements the WebhookEndpointsResponse interface.
 */
export function instanceOfWebhookEndpointsResponse(value: object): value is WebhookEndpointsResponse {
    if (!('webhooks' in value) || value['webhooks'] === undefined) return false;
    return true;
}

export function WebhookEndpointsResponseFromJSON(json: any): WebhookEndpointsResponse {
    return WebhookEndpointsResponseFromJSONTyped(json, false);
}

export function WebhookEndpointsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'webhooks': ((json['webhooks'] as Array<any>).map(WebhookEndpointSummaryFromJSON)),
    };
}

export function WebhookEndpointsResponseToJSON(json: any): WebhookEndpointsResponse {
    return WebhookEndpointsResponseToJSONTyped(json, false);
}

export function WebhookEndpointsResponseToJSONTyped(value?: WebhookEndpointsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhooks': ((value['webhooks'] as Array<any>).map(WebhookEndpointSummaryToJSON)),
    };
}

