# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cs2cap_sdk.models.threshold_value import ThresholdValue
from typing import Optional, Set
from typing_extensions import Self

class AlertCreateRequest(BaseModel):
    """
    AlertCreateRequest
    """ # noqa: E501
    item_id: StrictInt = Field(description="Normalized catalog item ID to monitor.")
    kind: StrictStr = Field(description="Alert kind: price_below, price_above, or spread_exceeds.")
    threshold_value: ThresholdValue
    threshold_currency: Optional[StrictStr] = None
    is_enabled: Optional[StrictBool] = Field(default=True, description="Whether the alert should be enabled immediately.")
    __properties: ClassVar[List[str]] = ["item_id", "kind", "threshold_value", "threshold_currency", "is_enabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlertCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of threshold_value
        if self.threshold_value:
            _dict['threshold_value'] = self.threshold_value.to_dict()
        # set to None if threshold_currency (nullable) is None
        # and model_fields_set contains the field
        if self.threshold_currency is None and "threshold_currency" in self.model_fields_set:
            _dict['threshold_currency'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlertCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "item_id": obj.get("item_id"),
            "kind": obj.get("kind"),
            "threshold_value": ThresholdValue.from_dict(obj["threshold_value"]) if obj.get("threshold_value") is not None else None,
            "threshold_currency": obj.get("threshold_currency"),
            "is_enabled": obj.get("is_enabled") if obj.get("is_enabled") is not None else True
        })
        return _obj


