# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AllProviders(str, Enum):
    """
    All available provider keys.  Members are generated from canonical endpoint metadata.
    """

    """
    allowed enum values
    """
    AVANMARKET = 'avanmarket'
    BITSKINS = 'bitskins'
    BUFF163 = 'buff163'
    BUFFMARKET = 'buffmarket'
    C5 = 'c5'
    CSDEALS = 'csdeals'
    CSFLOAT = 'csfloat'
    CSGO500 = 'csgo500'
    CSGOEMPIRE = 'csgoempire'
    CSMONEY_M = 'csmoney_m'
    CSMONEY_T = 'csmoney_t'
    CSTRADE = 'cstrade'
    DMARKET = 'dmarket'
    ECOSTEAM = 'ecosteam'
    GAMERPAY = 'gamerpay'
    HALOSKINS = 'haloskins'
    ITRADEGG = 'itradegg'
    LISSKINS = 'lisskins'
    LOOTFARM = 'lootfarm'
    MANNCO = 'mannco'
    MARKETCSGO = 'marketcsgo'
    PIRATESWAP = 'pirateswap'
    RAPIDSKINS = 'rapidskins'
    SHADOWPAY = 'shadowpay'
    SKINBARON = 'skinbaron'
    SKINFLOW = 'skinflow'
    SKINOUT = 'skinout'
    SKINPLACE = 'skinplace'
    SKINPORT = 'skinport'
    SKINSCOM = 'skinscom'
    SKINSMONKEY = 'skinsmonkey'
    SKINSWAP = 'skinswap'
    SKINVAULT = 'skinvault'
    STEAM = 'steam'
    SWAPGG = 'swapgg'
    TRADEIT = 'tradeit'
    WAXPEER = 'waxpeer'
    WHITEMARKET = 'whitemarket'
    YOUPIN = 'youpin'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AllProviders from a JSON string"""
        return cls(json.loads(json_str))


