# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class IndicatorVolatility(BaseModel):
    """
    Volatility indicator values.
    """ # noqa: E501
    atr_14: Optional[Union[StrictFloat, StrictInt]] = None
    historical_volatility_20: Optional[Union[StrictFloat, StrictInt]] = None
    kc_upper: Optional[Union[StrictFloat, StrictInt]] = None
    kc_middle: Optional[Union[StrictFloat, StrictInt]] = None
    kc_lower: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["atr_14", "historical_volatility_20", "kc_upper", "kc_middle", "kc_lower"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IndicatorVolatility from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if atr_14 (nullable) is None
        # and model_fields_set contains the field
        if self.atr_14 is None and "atr_14" in self.model_fields_set:
            _dict['atr_14'] = None

        # set to None if historical_volatility_20 (nullable) is None
        # and model_fields_set contains the field
        if self.historical_volatility_20 is None and "historical_volatility_20" in self.model_fields_set:
            _dict['historical_volatility_20'] = None

        # set to None if kc_upper (nullable) is None
        # and model_fields_set contains the field
        if self.kc_upper is None and "kc_upper" in self.model_fields_set:
            _dict['kc_upper'] = None

        # set to None if kc_middle (nullable) is None
        # and model_fields_set contains the field
        if self.kc_middle is None and "kc_middle" in self.model_fields_set:
            _dict['kc_middle'] = None

        # set to None if kc_lower (nullable) is None
        # and model_fields_set contains the field
        if self.kc_lower is None and "kc_lower" in self.model_fields_set:
            _dict['kc_lower'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IndicatorVolatility from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "atr_14": obj.get("atr_14"),
            "historical_volatility_20": obj.get("historical_volatility_20"),
            "kc_upper": obj.get("kc_upper"),
            "kc_middle": obj.get("kc_middle"),
            "kc_lower": obj.get("kc_lower")
        })
        return _obj


