# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from cs2cap_sdk.models.market_indicators_meta import MarketIndicatorsMeta
from cs2cap_sdk.models.market_indicators_screener_item import MarketIndicatorsScreenerItem
from cs2cap_sdk.models.pagination_meta import PaginationMeta
from typing import Optional, Set
from typing_extensions import Self

class MarketIndicatorsScreenerResponse(BaseModel):
    """
    Response envelope for /v1/market/indicators (bulk screener mode).
    """ # noqa: E501
    meta: MarketIndicatorsMeta = Field(description="Response metadata for this payload.")
    data: List[MarketIndicatorsScreenerItem] = Field(description="Primary data payload for this response.")
    pagination: PaginationMeta = Field(description="Pagination metadata for this response.")
    __properties: ClassVar[List[str]] = ["meta", "data", "pagination"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketIndicatorsScreenerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict['pagination'] = self.pagination.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketIndicatorsScreenerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "meta": MarketIndicatorsMeta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "data": [MarketIndicatorsScreenerItem.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
            "pagination": PaginationMeta.from_dict(obj["pagination"]) if obj.get("pagination") is not None else None
        })
        return _obj


