# coding: utf-8

"""
    CS2C-API

    CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Contact: dadscaptv@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from cs2cap_sdk.models.market_mover_item import MarketMoverItem
from typing import Optional, Set
from typing_extensions import Self

class MarketMoversData(BaseModel):
    """
    Movers endpoint payload.
    """ # noqa: E501
    gainers: List[MarketMoverItem] = Field(description="Items with positive movement for the selected window.")
    losers: List[MarketMoverItem] = Field(description="Items with negative movement for the selected window.")
    __properties: ClassVar[List[str]] = ["gainers", "losers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketMoversData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in gainers (list)
        _items = []
        if self.gainers:
            for _item_gainers in self.gainers:
                if _item_gainers:
                    _items.append(_item_gainers.to_dict())
            _dict['gainers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in losers (list)
        _items = []
        if self.losers:
            for _item_losers in self.losers:
                if _item_losers:
                    _items.append(_item_losers.to_dict())
            _dict['losers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketMoversData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gainers": [MarketMoverItem.from_dict(_item) for _item in obj["gainers"]] if obj.get("gainers") is not None else None,
            "losers": [MarketMoverItem.from_dict(_item) for _item in obj["losers"]] if obj.get("losers") is not None else None
        })
        return _obj


