# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cs2cap_sdk.models.charm_info import CharmInfo
from cs2cap_sdk.models.inspect_info import InspectInfo
from cs2cap_sdk.models.sticker_info import StickerInfo
from typing import Optional, Set
from typing_extensions import Self

class SaleRecordDetail(BaseModel):
    """
    Sale record matching CSFloat API response format.
    """ # noqa: E501
    var_date: datetime = Field(description="ISO 8601 UTC timestamp for this event.", alias="date")
    provider: StrictStr = Field(description="Provider key used by this API.")
    price: StrictInt = Field(description="Money amount in minor units of the response currency (for example USD cents when currency=USD). Divide by 100 for display.")
    currency: StrictStr = Field(description="ISO 4217 currency code for the value context.")
    item_id: StrictInt = Field(description="Normalized catalog item ID used by this API.")
    market_hash_name: StrictStr = Field(description="Canonical Steam market hash name for the item.")
    phase: Optional[StrictStr] = None
    var_float: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="float")
    paint_seed: Optional[StrictInt] = None
    stickers: Optional[List[StickerInfo]] = None
    charms: Optional[List[CharmInfo]] = None
    inspect: Optional[InspectInfo] = None
    __properties: ClassVar[List[str]] = ["date", "provider", "price", "currency", "item_id", "market_hash_name", "phase", "float", "paint_seed", "stickers", "charms", "inspect"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SaleRecordDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in stickers (list)
        _items = []
        if self.stickers:
            for _item_stickers in self.stickers:
                if _item_stickers:
                    _items.append(_item_stickers.to_dict())
            _dict['stickers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in charms (list)
        _items = []
        if self.charms:
            for _item_charms in self.charms:
                if _item_charms:
                    _items.append(_item_charms.to_dict())
            _dict['charms'] = _items
        # override the default output from pydantic by calling `to_dict()` of inspect
        if self.inspect:
            _dict['inspect'] = self.inspect.to_dict()
        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict['phase'] = None

        # set to None if var_float (nullable) is None
        # and model_fields_set contains the field
        if self.var_float is None and "var_float" in self.model_fields_set:
            _dict['float'] = None

        # set to None if paint_seed (nullable) is None
        # and model_fields_set contains the field
        if self.paint_seed is None and "paint_seed" in self.model_fields_set:
            _dict['paint_seed'] = None

        # set to None if stickers (nullable) is None
        # and model_fields_set contains the field
        if self.stickers is None and "stickers" in self.model_fields_set:
            _dict['stickers'] = None

        # set to None if charms (nullable) is None
        # and model_fields_set contains the field
        if self.charms is None and "charms" in self.model_fields_set:
            _dict['charms'] = None

        # set to None if inspect (nullable) is None
        # and model_fields_set contains the field
        if self.inspect is None and "inspect" in self.model_fields_set:
            _dict['inspect'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SaleRecordDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "provider": obj.get("provider"),
            "price": obj.get("price"),
            "currency": obj.get("currency"),
            "item_id": obj.get("item_id"),
            "market_hash_name": obj.get("market_hash_name"),
            "phase": obj.get("phase"),
            "float": obj.get("float"),
            "paint_seed": obj.get("paint_seed"),
            "stickers": [StickerInfo.from_dict(_item) for _item in obj["stickers"]] if obj.get("stickers") is not None else None,
            "charms": [CharmInfo.from_dict(_item) for _item in obj["charms"]] if obj.get("charms") is not None else None,
            "inspect": InspectInfo.from_dict(obj["inspect"]) if obj.get("inspect") is not None else None
        })
        return _obj


