# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cs2cap_sdk.models.charm_info import CharmInfo
from cs2cap_sdk.models.sticker_info import StickerInfo
from typing import Optional, Set
from typing_extensions import Self

class SteamInventoryItem(BaseModel):
    """
    A single item from a Steam CS2 inventory.
    """ # noqa: E501
    assetid: StrictStr = Field(description="Steam asset ID — unique per inventory slot.")
    market_hash_name: StrictStr = Field(description="Steam market hash name.")
    phase: Optional[StrictStr] = None
    name: StrictStr = Field(description="Display name.")
    icon_url: Optional[StrictStr] = None
    tradable: StrictBool = Field(description="Whether the item is currently tradable.")
    marketable: StrictBool = Field(description="Whether the item can be listed on the Steam Market.")
    quantity: StrictInt = Field(description="Stack size (almost always 1 for CS2 items).")
    float_value: Optional[Union[StrictFloat, StrictInt]] = None
    paint_seed: Optional[StrictInt] = None
    inspect_link: Optional[StrictStr] = None
    name_tag: Optional[StrictStr] = None
    stickers: Optional[List[StickerInfo]] = None
    charms: Optional[List[CharmInfo]] = None
    __properties: ClassVar[List[str]] = ["assetid", "market_hash_name", "phase", "name", "icon_url", "tradable", "marketable", "quantity", "float_value", "paint_seed", "inspect_link", "name_tag", "stickers", "charms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SteamInventoryItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in stickers (list)
        _items = []
        if self.stickers:
            for _item_stickers in self.stickers:
                if _item_stickers:
                    _items.append(_item_stickers.to_dict())
            _dict['stickers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in charms (list)
        _items = []
        if self.charms:
            for _item_charms in self.charms:
                if _item_charms:
                    _items.append(_item_charms.to_dict())
            _dict['charms'] = _items
        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict['phase'] = None

        # set to None if icon_url (nullable) is None
        # and model_fields_set contains the field
        if self.icon_url is None and "icon_url" in self.model_fields_set:
            _dict['icon_url'] = None

        # set to None if float_value (nullable) is None
        # and model_fields_set contains the field
        if self.float_value is None and "float_value" in self.model_fields_set:
            _dict['float_value'] = None

        # set to None if paint_seed (nullable) is None
        # and model_fields_set contains the field
        if self.paint_seed is None and "paint_seed" in self.model_fields_set:
            _dict['paint_seed'] = None

        # set to None if inspect_link (nullable) is None
        # and model_fields_set contains the field
        if self.inspect_link is None and "inspect_link" in self.model_fields_set:
            _dict['inspect_link'] = None

        # set to None if name_tag (nullable) is None
        # and model_fields_set contains the field
        if self.name_tag is None and "name_tag" in self.model_fields_set:
            _dict['name_tag'] = None

        # set to None if stickers (nullable) is None
        # and model_fields_set contains the field
        if self.stickers is None and "stickers" in self.model_fields_set:
            _dict['stickers'] = None

        # set to None if charms (nullable) is None
        # and model_fields_set contains the field
        if self.charms is None and "charms" in self.model_fields_set:
            _dict['charms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SteamInventoryItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "assetid": obj.get("assetid"),
            "market_hash_name": obj.get("market_hash_name"),
            "phase": obj.get("phase"),
            "name": obj.get("name"),
            "icon_url": obj.get("icon_url"),
            "tradable": obj.get("tradable"),
            "marketable": obj.get("marketable"),
            "quantity": obj.get("quantity"),
            "float_value": obj.get("float_value"),
            "paint_seed": obj.get("paint_seed"),
            "inspect_link": obj.get("inspect_link"),
            "name_tag": obj.get("name_tag"),
            "stickers": [StickerInfo.from_dict(_item) for _item in obj["stickers"]] if obj.get("stickers") is not None else None,
            "charms": [CharmInfo.from_dict(_item) for _item in obj["charms"]] if obj.get("charms") is not None else None
        })
        return _obj


