# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WebhookDeliverySummary(BaseModel):
    """
    Summary of one webhook delivery job.
    """ # noqa: E501
    id: StrictStr = Field(description="Unique delivery identifier.")
    event_id: StrictStr = Field(description="Associated alert event identifier.")
    endpoint_id: StrictStr = Field(description="Webhook destination identifier.")
    endpoint_label: StrictStr = Field(description="Snapshot of the destination label used for this delivery.")
    endpoint_url: StrictStr = Field(description="Snapshot of the destination URL used for this delivery.")
    event_type: StrictStr = Field(description="Outbound event type.")
    status: StrictStr = Field(description="Current delivery status.")
    attempt_count: StrictInt = Field(description="Number of delivery attempts recorded so far.")
    last_http_status: Optional[StrictInt] = None
    error: Optional[StrictStr] = None
    next_attempt_at: Optional[datetime] = None
    created_at: datetime = Field(description="ISO 8601 UTC timestamp when this delivery was created.")
    completed_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "event_id", "endpoint_id", "endpoint_label", "endpoint_url", "event_type", "status", "attempt_count", "last_http_status", "error", "next_attempt_at", "created_at", "completed_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookDeliverySummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_http_status (nullable) is None
        # and model_fields_set contains the field
        if self.last_http_status is None and "last_http_status" in self.model_fields_set:
            _dict['last_http_status'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if next_attempt_at (nullable) is None
        # and model_fields_set contains the field
        if self.next_attempt_at is None and "next_attempt_at" in self.model_fields_set:
            _dict['next_attempt_at'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookDeliverySummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "event_id": obj.get("event_id"),
            "endpoint_id": obj.get("endpoint_id"),
            "endpoint_label": obj.get("endpoint_label"),
            "endpoint_url": obj.get("endpoint_url"),
            "event_type": obj.get("event_type"),
            "status": obj.get("status"),
            "attempt_count": obj.get("attempt_count"),
            "last_http_status": obj.get("last_http_status"),
            "error": obj.get("error"),
            "next_attempt_at": obj.get("next_attempt_at"),
            "created_at": obj.get("created_at"),
            "completed_at": obj.get("completed_at")
        })
        return _obj


