/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  FXRatesResponse,
  ValidationErrorResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    FXRatesResponseFromJSON,
    FXRatesResponseToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class ForeignExchangeApi extends runtime.BaseAPI {

    /**
     * Creates request options for getFxRatesV1FxGet without sending the request
     */
    async getFxRatesV1FxGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/fx`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return latest foreign exchange rates.  Parameters: - None.  Response: - `timestamp`: ISO timestamp for the rates snapshot. - `rates`: Map of currency code to value relative to 1 USD (USD -> X).  Requirements: - Valid API key with access to `/v1/fx`.
     * Get Fx Rates
     */
    async getFxRatesV1FxGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FXRatesResponse>> {
        const requestOptions = await this.getFxRatesV1FxGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FXRatesResponseFromJSON(jsonValue));
    }

    /**
     * Return latest foreign exchange rates.  Parameters: - None.  Response: - `timestamp`: ISO timestamp for the rates snapshot. - `rates`: Map of currency code to value relative to 1 USD (USD -> X).  Requirements: - Valid API key with access to `/v1/fx`.
     * Get Fx Rates
     */
    async getFxRatesV1FxGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FXRatesResponse> {
        const response = await this.getFxRatesV1FxGetRaw(initOverrides);
        return await response.value();
    }

}
