/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  SteamInventoryResponse,
  ValidationErrorResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    SteamInventoryResponseFromJSON,
    SteamInventoryResponseToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface FetchSteamInventoryBySteamIdRequest {
    steamId: string;
}

/**
 * 
 */
export class InventoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for fetchSteamInventory without sending the request
     */
    async fetchSteamInventoryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/inventory/steam`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch the authenticated user\'s live CS2 inventory from Steam. Requires a linked Steam account. No data is persisted — use the portfolio import endpoint to add items to a portfolio.
     * Fetch Steam Inventory
     */
    async fetchSteamInventoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SteamInventoryResponse>> {
        const requestOptions = await this.fetchSteamInventoryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SteamInventoryResponseFromJSON(jsonValue));
    }

    /**
     * Fetch the authenticated user\'s live CS2 inventory from Steam. Requires a linked Steam account. No data is persisted — use the portfolio import endpoint to add items to a portfolio.
     * Fetch Steam Inventory
     */
    async fetchSteamInventory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SteamInventoryResponse> {
        const response = await this.fetchSteamInventoryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for fetchSteamInventoryBySteamId without sending the request
     */
    async fetchSteamInventoryBySteamIdRequestOpts(requestParameters: FetchSteamInventoryBySteamIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['steamId'] == null) {
            throw new runtime.RequiredError(
                'steamId',
                'Required parameter "steamId" was null or undefined when calling fetchSteamInventoryBySteamId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['steamId'] != null) {
            queryParameters['steam_id'] = requestParameters['steamId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/inventory/steam/lookup`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch the CS2 inventory for any Steam account by Steam64ID or vanity URL. Accepts a 17-digit Steam64ID (e.g. `76561197964243909`) or a custom URL name (e.g. `dadscap`). Vanity URL resolution requires a Steam Web API key to be configured. No data is persisted.
     * Fetch Steam Inventory by Steam ID
     */
    async fetchSteamInventoryBySteamIdRaw(requestParameters: FetchSteamInventoryBySteamIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SteamInventoryResponse>> {
        const requestOptions = await this.fetchSteamInventoryBySteamIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SteamInventoryResponseFromJSON(jsonValue));
    }

    /**
     * Fetch the CS2 inventory for any Steam account by Steam64ID or vanity URL. Accepts a 17-digit Steam64ID (e.g. `76561197964243909`) or a custom URL name (e.g. `dadscap`). Vanity URL resolution requires a Steam Web API key to be configured. No data is persisted.
     * Fetch Steam Inventory by Steam ID
     */
    async fetchSteamInventoryBySteamId(requestParameters: FetchSteamInventoryBySteamIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SteamInventoryResponse> {
        const response = await this.fetchSteamInventoryBySteamIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
