/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AllProviders,
  ErrorResponse,
  MarketArbitrageResponse,
  MarketItemAnalyticsResponse,
  MarketMoversResponse,
  MarketRankingListResponse,
  MaxPriceUsd,
  MinPriceUsd,
  MinVolumeUsd,
  ResponseGetIndicatorsV1MarketIndicatorsGet,
  ValidationErrorResponse,
} from '../models/index';
import {
    AllProvidersFromJSON,
    AllProvidersToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    MarketArbitrageResponseFromJSON,
    MarketArbitrageResponseToJSON,
    MarketItemAnalyticsResponseFromJSON,
    MarketItemAnalyticsResponseToJSON,
    MarketMoversResponseFromJSON,
    MarketMoversResponseToJSON,
    MarketRankingListResponseFromJSON,
    MarketRankingListResponseToJSON,
    MaxPriceUsdFromJSON,
    MaxPriceUsdToJSON,
    MinPriceUsdFromJSON,
    MinPriceUsdToJSON,
    MinVolumeUsdFromJSON,
    MinVolumeUsdToJSON,
    ResponseGetIndicatorsV1MarketIndicatorsGetFromJSON,
    ResponseGetIndicatorsV1MarketIndicatorsGetToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface GetArbitrageOpportunitiesV1MarketArbitrageGetRequest {
    limit?: number | null;
    cursor?: string | null;
    minSpreadPct?: number;
    providersBuy?: Array<AllProviders> | null;
    providersSell?: Array<AllProviders> | null;
}

export interface GetIndicatorsV1MarketIndicatorsGetRequest {
    itemId?: number | null;
    marketHashName?: string | null;
    phase?: string | null;
    provider?: string | null;
    interval?: GetIndicatorsV1MarketIndicatorsGetIntervalEnum;
    limit?: number | null;
    offset?: number;
    sortBy?: GetIndicatorsV1MarketIndicatorsGetSortByEnum;
    order?: GetIndicatorsV1MarketIndicatorsGetOrderEnum;
    currency?: string;
}

export interface GetItemAnalyticsV1MarketItemsItemIdGetRequest {
    itemId: number;
    timeframe?: GetItemAnalyticsV1MarketItemsItemIdGetTimeframeEnum;
    startAt?: Date | null;
    endAt?: Date | null;
}

export interface GetMarketMoversV1MarketMoversGetRequest {
    timeframe?: GetMarketMoversV1MarketMoversGetTimeframeEnum;
    startAt?: Date | null;
    endAt?: Date | null;
    limitPerSide?: number | null;
    providers?: Array<AllProviders> | null;
    minVolume?: number | null;
    minPriceUsd?: MinPriceUsd | null;
    maxPriceUsd?: MaxPriceUsd | null;
    sortBy?: GetMarketMoversV1MarketMoversGetSortByEnum;
    order?: GetMarketMoversV1MarketMoversGetOrderEnum;
}

export interface GetMarketRankingsV1MarketRankingsMetricGetRequest {
    metric: GetMarketRankingsV1MarketRankingsMetricGetMetricEnum;
    timeframe?: GetMarketRankingsV1MarketRankingsMetricGetTimeframeEnum;
    startAt?: Date | null;
    endAt?: Date | null;
    limit?: number | null;
    cursor?: string | null;
    order?: GetMarketRankingsV1MarketRankingsMetricGetOrderEnum;
    providers?: Array<AllProviders> | null;
    minVolatilityPct?: number | null;
    minVolumeUsd?: MinVolumeUsd | null;
    minLiquidityScore?: number | null;
}

/**
 * 
 */
export class MarketIntelligenceApi extends runtime.BaseAPI {

    /**
     * Creates request options for getArbitrageOpportunitiesV1MarketArbitrageGet without sending the request
     */
    async getArbitrageOpportunitiesV1MarketArbitrageGetRequestOpts(requestParameters: GetArbitrageOpportunitiesV1MarketArbitrageGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['minSpreadPct'] != null) {
            queryParameters['min_spread_pct'] = requestParameters['minSpreadPct'];
        }

        if (requestParameters['providersBuy'] != null) {
            queryParameters['providers_buy'] = requestParameters['providersBuy'];
        }

        if (requestParameters['providersSell'] != null) {
            queryParameters['providers_sell'] = requestParameters['providersSell'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/market/arbitrage`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Scan providers for cross-market arbitrage opportunities.  Filters: - `min_spread_pct` - `providers_buy` and `providers_sell` - cursor pagination via `cursor`  Response: - opportunities ranked by estimated net profit in USD with buy-side and sell-side provider context  Tier: Quant-only.
     * Get Arbitrage Opportunities
     */
    async getArbitrageOpportunitiesV1MarketArbitrageGetRaw(requestParameters: GetArbitrageOpportunitiesV1MarketArbitrageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarketArbitrageResponse>> {
        const requestOptions = await this.getArbitrageOpportunitiesV1MarketArbitrageGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarketArbitrageResponseFromJSON(jsonValue));
    }

    /**
     * Scan providers for cross-market arbitrage opportunities.  Filters: - `min_spread_pct` - `providers_buy` and `providers_sell` - cursor pagination via `cursor`  Response: - opportunities ranked by estimated net profit in USD with buy-side and sell-side provider context  Tier: Quant-only.
     * Get Arbitrage Opportunities
     */
    async getArbitrageOpportunitiesV1MarketArbitrageGet(requestParameters: GetArbitrageOpportunitiesV1MarketArbitrageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarketArbitrageResponse> {
        const response = await this.getArbitrageOpportunitiesV1MarketArbitrageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIndicatorsV1MarketIndicatorsGet without sending the request
     */
    async getIndicatorsV1MarketIndicatorsGetRequestOpts(requestParameters: GetIndicatorsV1MarketIndicatorsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['itemId'] != null) {
            queryParameters['item_id'] = requestParameters['itemId'];
        }

        if (requestParameters['marketHashName'] != null) {
            queryParameters['market_hash_name'] = requestParameters['marketHashName'];
        }

        if (requestParameters['phase'] != null) {
            queryParameters['phase'] = requestParameters['phase'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/market/indicators`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Compute technical analysis indicators from OHLCV candle data.  **Modes:**  - **Individual item**: Provide `item_id` (or `market_hash_name`) + `provider`.   Returns full numeric indicator values computed on-the-fly from candle data. - **Bulk screener**: Omit item filters. Returns signal summaries for top items   from pre-computed cache, paginated with offset.  **Indicators:**  - **Momentum**: RSI(14), MACD(12/26/9), SMA(20/50/200), EMA(12/26), Bollinger Bands(20,2σ) - **Volatility**: ATR(14), Historical Volatility(20), Keltner Channels(20/10/2) - **Volume**: VWAP, OBV, Volume SMA(20)  **Tier**: Quant-only.
     * Get Indicators
     */
    async getIndicatorsV1MarketIndicatorsGetRaw(requestParameters: GetIndicatorsV1MarketIndicatorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseGetIndicatorsV1MarketIndicatorsGet>> {
        const requestOptions = await this.getIndicatorsV1MarketIndicatorsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseGetIndicatorsV1MarketIndicatorsGetFromJSON(jsonValue));
    }

    /**
     * Compute technical analysis indicators from OHLCV candle data.  **Modes:**  - **Individual item**: Provide `item_id` (or `market_hash_name`) + `provider`.   Returns full numeric indicator values computed on-the-fly from candle data. - **Bulk screener**: Omit item filters. Returns signal summaries for top items   from pre-computed cache, paginated with offset.  **Indicators:**  - **Momentum**: RSI(14), MACD(12/26/9), SMA(20/50/200), EMA(12/26), Bollinger Bands(20,2σ) - **Volatility**: ATR(14), Historical Volatility(20), Keltner Channels(20/10/2) - **Volume**: VWAP, OBV, Volume SMA(20)  **Tier**: Quant-only.
     * Get Indicators
     */
    async getIndicatorsV1MarketIndicatorsGet(requestParameters: GetIndicatorsV1MarketIndicatorsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseGetIndicatorsV1MarketIndicatorsGet> {
        const response = await this.getIndicatorsV1MarketIndicatorsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getItemAnalyticsV1MarketItemsItemIdGet without sending the request
     */
    async getItemAnalyticsV1MarketItemsItemIdGetRequestOpts(requestParameters: GetItemAnalyticsV1MarketItemsItemIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getItemAnalyticsV1MarketItemsItemIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['startAt'] != null) {
            queryParameters['start_at'] = (requestParameters['startAt'] as any).toISOString();
        }

        if (requestParameters['endAt'] != null) {
            queryParameters['end_at'] = (requestParameters['endAt'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/market/items/{item_id}`;
        urlPath = urlPath.replace(`{${"item_id"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return per-item market analytics across providers for a requested time window.  Includes: - best ask, best bid, and spread summary - provider-level liquidity, volume, depth, and bid-side metrics - coverage diagnostics showing which providers contributed data  Window selection: - preset `timeframe` - or explicit `start_at` + `end_at`  Tier: Pro and Quant.
     * Get Item Analytics
     */
    async getItemAnalyticsV1MarketItemsItemIdGetRaw(requestParameters: GetItemAnalyticsV1MarketItemsItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarketItemAnalyticsResponse>> {
        const requestOptions = await this.getItemAnalyticsV1MarketItemsItemIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarketItemAnalyticsResponseFromJSON(jsonValue));
    }

    /**
     * Return per-item market analytics across providers for a requested time window.  Includes: - best ask, best bid, and spread summary - provider-level liquidity, volume, depth, and bid-side metrics - coverage diagnostics showing which providers contributed data  Window selection: - preset `timeframe` - or explicit `start_at` + `end_at`  Tier: Pro and Quant.
     * Get Item Analytics
     */
    async getItemAnalyticsV1MarketItemsItemIdGet(requestParameters: GetItemAnalyticsV1MarketItemsItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarketItemAnalyticsResponse> {
        const response = await this.getItemAnalyticsV1MarketItemsItemIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMarketMoversV1MarketMoversGet without sending the request
     */
    async getMarketMoversV1MarketMoversGetRequestOpts(requestParameters: GetMarketMoversV1MarketMoversGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['startAt'] != null) {
            queryParameters['start_at'] = (requestParameters['startAt'] as any).toISOString();
        }

        if (requestParameters['endAt'] != null) {
            queryParameters['end_at'] = (requestParameters['endAt'] as any).toISOString();
        }

        if (requestParameters['limitPerSide'] != null) {
            queryParameters['limit_per_side'] = requestParameters['limitPerSide'];
        }

        if (requestParameters['providers'] != null) {
            queryParameters['providers'] = requestParameters['providers'];
        }

        if (requestParameters['minVolume'] != null) {
            queryParameters['min_volume'] = requestParameters['minVolume'];
        }

        if (requestParameters['minPriceUsd'] != null) {
            queryParameters['min_price_usd'] = requestParameters['minPriceUsd'];
        }

        if (requestParameters['maxPriceUsd'] != null) {
            queryParameters['max_price_usd'] = requestParameters['maxPriceUsd'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/market/movers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the top gainers and losers for a requested analysis window.  Filters: - `timeframe` or explicit `start_at` + `end_at` - `providers`, `min_volume`, `min_price_usd`, `max_price_usd` - `sort_by` and `order`  Response: - `meta`: generation time, data source, freshness, and effective window - `data.gainers`: positive movers for the selected window - `data.losers`: negative movers for the selected window  Tier: Quant-only.
     * Get Market Movers
     */
    async getMarketMoversV1MarketMoversGetRaw(requestParameters: GetMarketMoversV1MarketMoversGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarketMoversResponse>> {
        const requestOptions = await this.getMarketMoversV1MarketMoversGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarketMoversResponseFromJSON(jsonValue));
    }

    /**
     * Return the top gainers and losers for a requested analysis window.  Filters: - `timeframe` or explicit `start_at` + `end_at` - `providers`, `min_volume`, `min_price_usd`, `max_price_usd` - `sort_by` and `order`  Response: - `meta`: generation time, data source, freshness, and effective window - `data.gainers`: positive movers for the selected window - `data.losers`: negative movers for the selected window  Tier: Quant-only.
     * Get Market Movers
     */
    async getMarketMoversV1MarketMoversGet(requestParameters: GetMarketMoversV1MarketMoversGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarketMoversResponse> {
        const response = await this.getMarketMoversV1MarketMoversGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMarketRankingsV1MarketRankingsMetricGet without sending the request
     */
    async getMarketRankingsV1MarketRankingsMetricGetRequestOpts(requestParameters: GetMarketRankingsV1MarketRankingsMetricGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['metric'] == null) {
            throw new runtime.RequiredError(
                'metric',
                'Required parameter "metric" was null or undefined when calling getMarketRankingsV1MarketRankingsMetricGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['startAt'] != null) {
            queryParameters['start_at'] = (requestParameters['startAt'] as any).toISOString();
        }

        if (requestParameters['endAt'] != null) {
            queryParameters['end_at'] = (requestParameters['endAt'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['providers'] != null) {
            queryParameters['providers'] = requestParameters['providers'];
        }

        if (requestParameters['minVolatilityPct'] != null) {
            queryParameters['min_volatility_pct'] = requestParameters['minVolatilityPct'];
        }

        if (requestParameters['minVolumeUsd'] != null) {
            queryParameters['min_volume_usd'] = requestParameters['minVolumeUsd'];
        }

        if (requestParameters['minLiquidityScore'] != null) {
            queryParameters['min_liquidity_score'] = requestParameters['minLiquidityScore'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/market/rankings/{metric}`;
        urlPath = urlPath.replace(`{${"metric"}}`, encodeURIComponent(String(requestParameters['metric'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return ranked market analytics rows for one metric with cursor pagination.  Supported metrics: - `volatility` - `volume` - `liquidity`  Filters: - `timeframe` or explicit `start_at` + `end_at` - `providers` - metric-specific minimum thresholds such as `min_volatility_pct`, `min_volume_usd`, and `min_liquidity_score` - `order`  Response: - ranked items list plus cursor pagination metadata  Tier: Quant-only.
     * Get Market Rankings
     */
    async getMarketRankingsV1MarketRankingsMetricGetRaw(requestParameters: GetMarketRankingsV1MarketRankingsMetricGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarketRankingListResponse>> {
        const requestOptions = await this.getMarketRankingsV1MarketRankingsMetricGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarketRankingListResponseFromJSON(jsonValue));
    }

    /**
     * Return ranked market analytics rows for one metric with cursor pagination.  Supported metrics: - `volatility` - `volume` - `liquidity`  Filters: - `timeframe` or explicit `start_at` + `end_at` - `providers` - metric-specific minimum thresholds such as `min_volatility_pct`, `min_volume_usd`, and `min_liquidity_score` - `order`  Response: - ranked items list plus cursor pagination metadata  Tier: Quant-only.
     * Get Market Rankings
     */
    async getMarketRankingsV1MarketRankingsMetricGet(requestParameters: GetMarketRankingsV1MarketRankingsMetricGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarketRankingListResponse> {
        const response = await this.getMarketRankingsV1MarketRankingsMetricGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetIndicatorsV1MarketIndicatorsGetIntervalEnum = {
    _1h: '1h',
    _1d: '1d'
} as const;
export type GetIndicatorsV1MarketIndicatorsGetIntervalEnum = typeof GetIndicatorsV1MarketIndicatorsGetIntervalEnum[keyof typeof GetIndicatorsV1MarketIndicatorsGetIntervalEnum];
/**
 * @export
 */
export const GetIndicatorsV1MarketIndicatorsGetSortByEnum = {
    CompositeScore: 'composite_score',
    Rsi14: 'rsi_14',
    MacdHistogram: 'macd_histogram',
    Atr14: 'atr_14'
} as const;
export type GetIndicatorsV1MarketIndicatorsGetSortByEnum = typeof GetIndicatorsV1MarketIndicatorsGetSortByEnum[keyof typeof GetIndicatorsV1MarketIndicatorsGetSortByEnum];
/**
 * @export
 */
export const GetIndicatorsV1MarketIndicatorsGetOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetIndicatorsV1MarketIndicatorsGetOrderEnum = typeof GetIndicatorsV1MarketIndicatorsGetOrderEnum[keyof typeof GetIndicatorsV1MarketIndicatorsGetOrderEnum];
/**
 * @export
 */
export const GetItemAnalyticsV1MarketItemsItemIdGetTimeframeEnum = {
    _1h: '1h',
    _24h: '24h',
    _7d: '7d',
    _30d: '30d'
} as const;
export type GetItemAnalyticsV1MarketItemsItemIdGetTimeframeEnum = typeof GetItemAnalyticsV1MarketItemsItemIdGetTimeframeEnum[keyof typeof GetItemAnalyticsV1MarketItemsItemIdGetTimeframeEnum];
/**
 * @export
 */
export const GetMarketMoversV1MarketMoversGetTimeframeEnum = {
    _1h: '1h',
    _24h: '24h',
    _7d: '7d',
    _30d: '30d'
} as const;
export type GetMarketMoversV1MarketMoversGetTimeframeEnum = typeof GetMarketMoversV1MarketMoversGetTimeframeEnum[keyof typeof GetMarketMoversV1MarketMoversGetTimeframeEnum];
/**
 * @export
 */
export const GetMarketMoversV1MarketMoversGetSortByEnum = {
    PriceChangeAbs: 'price_change_abs',
    PriceChangePct: 'price_change_pct',
    Volume: 'volume',
    CurrentPrice: 'current_price'
} as const;
export type GetMarketMoversV1MarketMoversGetSortByEnum = typeof GetMarketMoversV1MarketMoversGetSortByEnum[keyof typeof GetMarketMoversV1MarketMoversGetSortByEnum];
/**
 * @export
 */
export const GetMarketMoversV1MarketMoversGetOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetMarketMoversV1MarketMoversGetOrderEnum = typeof GetMarketMoversV1MarketMoversGetOrderEnum[keyof typeof GetMarketMoversV1MarketMoversGetOrderEnum];
/**
 * @export
 */
export const GetMarketRankingsV1MarketRankingsMetricGetMetricEnum = {
    Volatility: 'volatility',
    Volume: 'volume',
    Liquidity: 'liquidity'
} as const;
export type GetMarketRankingsV1MarketRankingsMetricGetMetricEnum = typeof GetMarketRankingsV1MarketRankingsMetricGetMetricEnum[keyof typeof GetMarketRankingsV1MarketRankingsMetricGetMetricEnum];
/**
 * @export
 */
export const GetMarketRankingsV1MarketRankingsMetricGetTimeframeEnum = {
    _1h: '1h',
    _24h: '24h',
    _7d: '7d',
    _30d: '30d'
} as const;
export type GetMarketRankingsV1MarketRankingsMetricGetTimeframeEnum = typeof GetMarketRankingsV1MarketRankingsMetricGetTimeframeEnum[keyof typeof GetMarketRankingsV1MarketRankingsMetricGetTimeframeEnum];
/**
 * @export
 */
export const GetMarketRankingsV1MarketRankingsMetricGetOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetMarketRankingsV1MarketRankingsMetricGetOrderEnum = typeof GetMarketRankingsV1MarketRankingsMetricGetOrderEnum[keyof typeof GetMarketRankingsV1MarketRankingsMetricGetOrderEnum];
