/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PortfolioAddItemRequest,
  PortfolioCreate,
  PortfolioHistoryPage,
  PortfolioImportRequest,
  PortfolioImportResult,
  PortfolioItemOut,
  PortfolioListResponse,
  PortfolioOut,
  PortfolioRequest,
  PortfolioResponse,
  TransactionCreateRequest,
  TransactionOut,
  TransactionUpdateRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PortfolioAddItemRequestFromJSON,
    PortfolioAddItemRequestToJSON,
    PortfolioCreateFromJSON,
    PortfolioCreateToJSON,
    PortfolioHistoryPageFromJSON,
    PortfolioHistoryPageToJSON,
    PortfolioImportRequestFromJSON,
    PortfolioImportRequestToJSON,
    PortfolioImportResultFromJSON,
    PortfolioImportResultToJSON,
    PortfolioItemOutFromJSON,
    PortfolioItemOutToJSON,
    PortfolioListResponseFromJSON,
    PortfolioListResponseToJSON,
    PortfolioOutFromJSON,
    PortfolioOutToJSON,
    PortfolioRequestFromJSON,
    PortfolioRequestToJSON,
    PortfolioResponseFromJSON,
    PortfolioResponseToJSON,
    TransactionCreateRequestFromJSON,
    TransactionCreateRequestToJSON,
    TransactionOutFromJSON,
    TransactionOutToJSON,
    TransactionUpdateRequestFromJSON,
    TransactionUpdateRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface AddItemToPortfolioRequest {
    portfolioId: string;
    portfolioAddItemRequest: PortfolioAddItemRequest;
}

export interface AddTransactionRequest {
    portfolioId: string;
    transactionCreateRequest: TransactionCreateRequest;
}

export interface CreatePortfolioRequest {
    portfolioCreate: PortfolioCreate;
}

export interface DeletePortfolioRequest {
    portfolioId: string;
}

export interface DeleteTransactionRequest {
    portfolioId: string;
    transactionId: string;
}

export interface HistoricalSavedPortfolioValuationRequest {
    portfolioId: string;
    startDate?: Date | null;
    endDate?: Date | null;
    lookback?: string | null;
    currency?: string;
    providers?: Array<string> | null;
    limit?: number | null;
    cursor?: string | null;
}

export interface ImportSteamInventoryRequest {
    portfolioId: string;
    portfolioImportRequest: PortfolioImportRequest;
}

export interface ListPortfolioItemsRequest {
    portfolioId: string;
}

export interface ListTransactionsRequest {
    portfolioId: string;
}

export interface PortfolioValuationRequest {
    portfolioRequest: PortfolioRequest;
}

export interface RemoveItemFromPortfolioRequest {
    portfolioId: string;
    entryId: string;
}

export interface UpdateTransactionRequest {
    portfolioId: string;
    transactionId: string;
    transactionUpdateRequest: TransactionUpdateRequest;
}

export interface ValueSavedPortfolioRequest {
    portfolioId: string;
    currency?: string;
    providers?: Array<string> | null;
}

/**
 * 
 */
export class PortfolioApi extends runtime.BaseAPI {

    /**
     * Creates request options for addItemToPortfolio without sending the request
     */
    async addItemToPortfolioRequestOpts(requestParameters: AddItemToPortfolioRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling addItemToPortfolio().'
            );
        }

        if (requestParameters['portfolioAddItemRequest'] == null) {
            throw new runtime.RequiredError(
                'portfolioAddItemRequest',
                'Required parameter "portfolioAddItemRequest" was null or undefined when calling addItemToPortfolio().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/items`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioAddItemRequestToJSON(requestParameters['portfolioAddItemRequest']),
        };
    }

    /**
     * Add a single item to a portfolio by `item_id` or `market_hash_name`. Use this for manual entry without a Steam inventory import.
     * Add Item to Portfolio
     */
    async addItemToPortfolioRaw(requestParameters: AddItemToPortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioItemOut>> {
        const requestOptions = await this.addItemToPortfolioRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioItemOutFromJSON(jsonValue));
    }

    /**
     * Add a single item to a portfolio by `item_id` or `market_hash_name`. Use this for manual entry without a Steam inventory import.
     * Add Item to Portfolio
     */
    async addItemToPortfolio(requestParameters: AddItemToPortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioItemOut> {
        const response = await this.addItemToPortfolioRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addTransaction without sending the request
     */
    async addTransactionRequestOpts(requestParameters: AddTransactionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling addTransaction().'
            );
        }

        if (requestParameters['transactionCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'transactionCreateRequest',
                'Required parameter "transactionCreateRequest" was null or undefined when calling addTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/transactions`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionCreateRequestToJSON(requestParameters['transactionCreateRequest']),
        };
    }

    /**
     * Record a buy or sell transaction for an item in this portfolio.
     * Add Transaction
     */
    async addTransactionRaw(requestParameters: AddTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionOut>> {
        const requestOptions = await this.addTransactionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionOutFromJSON(jsonValue));
    }

    /**
     * Record a buy or sell transaction for an item in this portfolio.
     * Add Transaction
     */
    async addTransaction(requestParameters: AddTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionOut> {
        const response = await this.addTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPortfolio without sending the request
     */
    async createPortfolioRequestOpts(requestParameters: CreatePortfolioRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioCreate'] == null) {
            throw new runtime.RequiredError(
                'portfolioCreate',
                'Required parameter "portfolioCreate" was null or undefined when calling createPortfolio().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioCreateToJSON(requestParameters['portfolioCreate']),
        };
    }

    /**
     * Create a new named portfolio. The maximum number of portfolios depends on your tier. Portfolios store items persistently and can be valued at any time.
     * Create Portfolio
     */
    async createPortfolioRaw(requestParameters: CreatePortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioOut>> {
        const requestOptions = await this.createPortfolioRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioOutFromJSON(jsonValue));
    }

    /**
     * Create a new named portfolio. The maximum number of portfolios depends on your tier. Portfolios store items persistently and can be valued at any time.
     * Create Portfolio
     */
    async createPortfolio(requestParameters: CreatePortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioOut> {
        const response = await this.createPortfolioRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePortfolio without sending the request
     */
    async deletePortfolioRequestOpts(requestParameters: DeletePortfolioRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling deletePortfolio().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a portfolio and all its items.
     * Delete Portfolio
     */
    async deletePortfolioRaw(requestParameters: DeletePortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePortfolioRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a portfolio and all its items.
     * Delete Portfolio
     */
    async deletePortfolio(requestParameters: DeletePortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePortfolioRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteTransaction without sending the request
     */
    async deleteTransactionRequestOpts(requestParameters: DeleteTransactionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling deleteTransaction().'
            );
        }

        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling deleteTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/transactions/{transaction_id}`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));
        urlPath = urlPath.replace(`{${"transaction_id"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a transaction from a portfolio.
     * Delete Transaction
     */
    async deleteTransactionRaw(requestParameters: DeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTransactionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a transaction from a portfolio.
     * Delete Transaction
     */
    async deleteTransaction(requestParameters: DeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTransactionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for historicalSavedPortfolioValuation without sending the request
     */
    async historicalSavedPortfolioValuationRequestOpts(requestParameters: HistoricalSavedPortfolioValuationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling historicalSavedPortfolioValuation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['lookback'] != null) {
            queryParameters['lookback'] = requestParameters['lookback'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['providers'] != null) {
            queryParameters['providers'] = requestParameters['providers'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/history`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Replay saved-portfolio holdings from the transaction ledger and return daily historical valuation points priced from stored daily market closes. This endpoint is daily-only because portfolio transactions are date-granular.
     * Historical Saved Portfolio Valuation
     */
    async historicalSavedPortfolioValuationRaw(requestParameters: HistoricalSavedPortfolioValuationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioHistoryPage>> {
        const requestOptions = await this.historicalSavedPortfolioValuationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioHistoryPageFromJSON(jsonValue));
    }

    /**
     * Replay saved-portfolio holdings from the transaction ledger and return daily historical valuation points priced from stored daily market closes. This endpoint is daily-only because portfolio transactions are date-granular.
     * Historical Saved Portfolio Valuation
     */
    async historicalSavedPortfolioValuation(requestParameters: HistoricalSavedPortfolioValuationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioHistoryPage> {
        const response = await this.historicalSavedPortfolioValuationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for importSteamInventory without sending the request
     */
    async importSteamInventoryRequestOpts(requestParameters: ImportSteamInventoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling importSteamInventory().'
            );
        }

        if (requestParameters['portfolioImportRequest'] == null) {
            throw new runtime.RequiredError(
                'portfolioImportRequest',
                'Required parameter "portfolioImportRequest" was null or undefined when calling importSteamInventory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/import`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioImportRequestToJSON(requestParameters['portfolioImportRequest']),
        };
    }

    /**
     * Import items from the user\'s Steam inventory into a portfolio. Optionally supply `asset_ids` to import only specific items. Items already present (by Steam asset ID) are skipped. Items not matched in the CS2C catalog are returned in `unresolved` and are not stored.
     * Import Steam Inventory
     */
    async importSteamInventoryRaw(requestParameters: ImportSteamInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioImportResult>> {
        const requestOptions = await this.importSteamInventoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioImportResultFromJSON(jsonValue));
    }

    /**
     * Import items from the user\'s Steam inventory into a portfolio. Optionally supply `asset_ids` to import only specific items. Items already present (by Steam asset ID) are skipped. Items not matched in the CS2C catalog are returned in `unresolved` and are not stored.
     * Import Steam Inventory
     */
    async importSteamInventory(requestParameters: ImportSteamInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioImportResult> {
        const response = await this.importSteamInventoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPortfolioItems without sending the request
     */
    async listPortfolioItemsRequestOpts(requestParameters: ListPortfolioItemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling listPortfolioItems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/items`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all items in a saved portfolio.
     * List Portfolio Items
     */
    async listPortfolioItemsRaw(requestParameters: ListPortfolioItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PortfolioItemOut>>> {
        const requestOptions = await this.listPortfolioItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PortfolioItemOutFromJSON));
    }

    /**
     * List all items in a saved portfolio.
     * List Portfolio Items
     */
    async listPortfolioItems(requestParameters: ListPortfolioItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PortfolioItemOut>> {
        const response = await this.listPortfolioItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPortfolios without sending the request
     */
    async listPortfoliosRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all named portfolios belonging to the authenticated user.
     * List Portfolios
     */
    async listPortfoliosRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioListResponse>> {
        const requestOptions = await this.listPortfoliosRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioListResponseFromJSON(jsonValue));
    }

    /**
     * List all named portfolios belonging to the authenticated user.
     * List Portfolios
     */
    async listPortfolios(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioListResponse> {
        const response = await this.listPortfoliosRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTransactions without sending the request
     */
    async listTransactionsRequestOpts(requestParameters: ListTransactionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling listTransactions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/transactions`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all transactions in a portfolio, newest first.
     * List Transactions
     */
    async listTransactionsRaw(requestParameters: ListTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TransactionOut>>> {
        const requestOptions = await this.listTransactionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TransactionOutFromJSON));
    }

    /**
     * List all transactions in a portfolio, newest first.
     * List Transactions
     */
    async listTransactions(requestParameters: ListTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TransactionOut>> {
        const response = await this.listTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for portfolioValuation without sending the request
     */
    async portfolioValuationRequestOpts(requestParameters: PortfolioValuationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioRequest'] == null) {
            throw new runtime.RequiredError(
                'portfolioRequest',
                'Required parameter "portfolioRequest" was null or undefined when calling portfolioValuation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/value`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioRequestToJSON(requestParameters['portfolioRequest']),
        };
    }

    /**
     * Value an inventory of CS2 items at live market prices.  Send a list of `{item_id, quantity}` pairs and receive per-item valuation based on the best ask price across queried providers, plus a rolled-up total.  Maximum 100 distinct items per request.  All money values are in minor units of the requested currency (e.g. USD cents when `currency=USD`). Divide by 100 for display.
     * Portfolio Valuation
     */
    async portfolioValuationRaw(requestParameters: PortfolioValuationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioResponse>> {
        const requestOptions = await this.portfolioValuationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioResponseFromJSON(jsonValue));
    }

    /**
     * Value an inventory of CS2 items at live market prices.  Send a list of `{item_id, quantity}` pairs and receive per-item valuation based on the best ask price across queried providers, plus a rolled-up total.  Maximum 100 distinct items per request.  All money values are in minor units of the requested currency (e.g. USD cents when `currency=USD`). Divide by 100 for display.
     * Portfolio Valuation
     */
    async portfolioValuation(requestParameters: PortfolioValuationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioResponse> {
        const response = await this.portfolioValuationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeItemFromPortfolio without sending the request
     */
    async removeItemFromPortfolioRequestOpts(requestParameters: RemoveItemFromPortfolioRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling removeItemFromPortfolio().'
            );
        }

        if (requestParameters['entryId'] == null) {
            throw new runtime.RequiredError(
                'entryId',
                'Required parameter "entryId" was null or undefined when calling removeItemFromPortfolio().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/items/{entry_id}`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));
        urlPath = urlPath.replace(`{${"entry_id"}}`, encodeURIComponent(String(requestParameters['entryId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a specific item entry from a portfolio.
     * Remove Item from Portfolio
     */
    async removeItemFromPortfolioRaw(requestParameters: RemoveItemFromPortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeItemFromPortfolioRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a specific item entry from a portfolio.
     * Remove Item from Portfolio
     */
    async removeItemFromPortfolio(requestParameters: RemoveItemFromPortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeItemFromPortfolioRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateTransaction without sending the request
     */
    async updateTransactionRequestOpts(requestParameters: UpdateTransactionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling updateTransaction().'
            );
        }

        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling updateTransaction().'
            );
        }

        if (requestParameters['transactionUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'transactionUpdateRequest',
                'Required parameter "transactionUpdateRequest" was null or undefined when calling updateTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/transactions/{transaction_id}`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));
        urlPath = urlPath.replace(`{${"transaction_id"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionUpdateRequestToJSON(requestParameters['transactionUpdateRequest']),
        };
    }

    /**
     * Partially update a transaction.
     * Update Transaction
     */
    async updateTransactionRaw(requestParameters: UpdateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionOut>> {
        const requestOptions = await this.updateTransactionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionOutFromJSON(jsonValue));
    }

    /**
     * Partially update a transaction.
     * Update Transaction
     */
    async updateTransaction(requestParameters: UpdateTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionOut> {
        const response = await this.updateTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for valueSavedPortfolio without sending the request
     */
    async valueSavedPortfolioRequestOpts(requestParameters: ValueSavedPortfolioRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['portfolioId'] == null) {
            throw new runtime.RequiredError(
                'portfolioId',
                'Required parameter "portfolioId" was null or undefined when calling valueSavedPortfolio().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['providers'] != null) {
            queryParameters['providers'] = requestParameters['providers'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/portfolio/{portfolio_id}/value`;
        urlPath = urlPath.replace(`{${"portfolio_id"}}`, encodeURIComponent(String(requestParameters['portfolioId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Value all items in a saved portfolio at live market prices. Items without price data appear in `items_not_found`. All money values are in minor units (e.g. USD cents). Divide by 100 for display.
     * Value Saved Portfolio
     */
    async valueSavedPortfolioRaw(requestParameters: ValueSavedPortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioResponse>> {
        const requestOptions = await this.valueSavedPortfolioRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioResponseFromJSON(jsonValue));
    }

    /**
     * Value all items in a saved portfolio at live market prices. Items without price data appear in `items_not_found`. All money values are in minor units (e.g. USD cents). Divide by 100 for display.
     * Value Saved Portfolio
     */
    async valueSavedPortfolio(requestParameters: ValueSavedPortfolioRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioResponse> {
        const response = await this.valueSavedPortfolioRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
