/* tslint:disable */
/* eslint-disable */
/**
 * CS2C-API
 * CS2C-API aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dadscaptv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ProviderInfo,
  ValidationErrorResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ProviderInfoFromJSON,
    ProviderInfoToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface ListProvidersV1ProvidersGetRequest {
    provider?: string | null;
}

/**
 * 
 */
export class ProvidersApi extends runtime.BaseAPI {

    /**
     * Creates request options for listProvidersV1ProvidersGet without sending the request
     */
    async listProvidersV1ProvidersGetRequestOpts(requestParameters: ListProvidersV1ProvidersGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List supported marketplace providers with capability, fee, currency, and health metadata.  Use the optional `provider` query parameter to fetch a single provider by key.
     * List Providers
     */
    async listProvidersV1ProvidersGetRaw(requestParameters: ListProvidersV1ProvidersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: ProviderInfo; }>> {
        const requestOptions = await this.listProvidersV1ProvidersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, ProviderInfoFromJSON));
    }

    /**
     * List supported marketplace providers with capability, fee, currency, and health metadata.  Use the optional `provider` query parameter to fetch a single provider by key.
     * List Providers
     */
    async listProvidersV1ProvidersGet(requestParameters: ListProvidersV1ProvidersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: ProviderInfo; }> {
        const response = await this.listProvidersV1ProvidersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
