/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PhaseName,
  RecentSalesProvider,
  SalesHistoryResponse,
  ValidationErrorResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PhaseNameFromJSON,
    PhaseNameToJSON,
    RecentSalesProviderFromJSON,
    RecentSalesProviderToJSON,
    SalesHistoryResponseFromJSON,
    SalesHistoryResponseToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface ListRecentSalesRequest {
    itemId?: number | null;
    marketHashName?: string | null;
    phase?: PhaseName | null;
    providers?: Array<RecentSalesProvider> | null;
    currency?: string;
    limit?: number | null;
}

/**
 * 
 */
export class SalesApi extends runtime.BaseAPI {

    /**
     * Creates request options for listRecentSales without sending the request
     */
    async listRecentSalesRequestOpts(requestParameters: ListRecentSalesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['itemId'] != null) {
            queryParameters['item_id'] = requestParameters['itemId'];
        }

        if (requestParameters['marketHashName'] != null) {
            queryParameters['market_hash_name'] = requestParameters['marketHashName'];
        }

        if (requestParameters['phase'] != null) {
            queryParameters['phase'] = requestParameters['phase'];
        }

        if (requestParameters['providers'] != null) {
            queryParameters['providers'] = requestParameters['providers'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sales`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return recent sales history from providers with recent-sales support.  Filters: - `item_id` or `market_hash_name` is required - optional `phase` - `providers` limited to sales-capable provider keys - `currency` and `limit`  Behavior: - cache misses trigger live provider fetches during the request - results are cached per item and provider for 1 hour - response is single-page only with a maximum of 50 rows  Response: - request metadata and providers queried - sales records with sticker, charm, and inspect metadata when available - per-provider cache status for hit, miss, error, or unavailable
     * List Recent Sales
     */
    async listRecentSalesRaw(requestParameters: ListRecentSalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SalesHistoryResponse>> {
        const requestOptions = await this.listRecentSalesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalesHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Return recent sales history from providers with recent-sales support.  Filters: - `item_id` or `market_hash_name` is required - optional `phase` - `providers` limited to sales-capable provider keys - `currency` and `limit`  Behavior: - cache misses trigger live provider fetches during the request - results are cached per item and provider for 1 hour - response is single-page only with a maximum of 50 rows  Response: - request metadata and providers queried - sales records with sticker, charm, and inspect metadata when available - per-provider cache status for hit, miss, error, or unavailable
     * List Recent Sales
     */
    async listRecentSales(requestParameters: ListRecentSalesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SalesHistoryResponse> {
        const response = await this.listRecentSalesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
