# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cs2cap.models.market_item_analytics_coverage import MarketItemAnalyticsCoverage
from cs2cap.models.market_item_analytics_provider import MarketItemAnalyticsProvider
from cs2cap.models.market_item_analytics_summary import MarketItemAnalyticsSummary
from typing import Optional, Set
from typing_extensions import Self

class MarketItemAnalyticsData(BaseModel):
    """
    Payload for /v1/market/items/{item_id}.
    """ # noqa: E501
    item_id: StrictInt = Field(description="Normalized catalog item ID used by this API.")
    market_hash_name: StrictStr = Field(description="Canonical Steam market hash name for the item.")
    phase: Optional[StrictStr] = None
    summary: MarketItemAnalyticsSummary = Field(description="Summary value.")
    providers: List[MarketItemAnalyticsProvider] = Field(description="Providers value.")
    coverage: MarketItemAnalyticsCoverage = Field(description="Coverage value.")
    __properties: ClassVar[List[str]] = ["item_id", "market_hash_name", "phase", "summary", "providers", "coverage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketItemAnalyticsData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in providers (list)
        _items = []
        if self.providers:
            for _item_providers in self.providers:
                if _item_providers:
                    _items.append(_item_providers.to_dict())
            _dict['providers'] = _items
        # override the default output from pydantic by calling `to_dict()` of coverage
        if self.coverage:
            _dict['coverage'] = self.coverage.to_dict()
        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict['phase'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketItemAnalyticsData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "item_id": obj.get("item_id"),
            "market_hash_name": obj.get("market_hash_name"),
            "phase": obj.get("phase"),
            "summary": MarketItemAnalyticsSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "providers": [MarketItemAnalyticsProvider.from_dict(_item) for _item in obj["providers"]] if obj.get("providers") is not None else None,
            "coverage": MarketItemAnalyticsCoverage.from_dict(obj["coverage"]) if obj.get("coverage") is not None else None
        })
        return _obj


