# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cs2cap.models.provider_features import ProviderFeatures
from cs2cap.models.provider_fees import ProviderFees
from cs2cap.models.provider_health import ProviderHealth
from typing import Optional, Set
from typing_extensions import Self

class ProviderInfo(BaseModel):
    """
    ProviderInfo
    """ # noqa: E501
    key: StrictStr = Field(description="Stable provider key used in request and response payloads.")
    logo: StrictStr = Field(description="CDN URL for the provider logo asset.")
    code: Optional[StrictStr] = None
    market_type: Optional[StrictStr] = None
    default_currency: Optional[StrictStr] = None
    fees: ProviderFees = Field(description="Fee configuration values keyed by fee type.")
    features: ProviderFeatures = Field(description="Feature capability flags for this provider.")
    health: ProviderHealth = Field(description="Provider health metrics and aggregate diagnostics.")
    __properties: ClassVar[List[str]] = ["key", "logo", "code", "market_type", "default_currency", "fees", "features", "health"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProviderInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of fees
        if self.fees:
            _dict['fees'] = self.fees.to_dict()
        # override the default output from pydantic by calling `to_dict()` of features
        if self.features:
            _dict['features'] = self.features.to_dict()
        # override the default output from pydantic by calling `to_dict()` of health
        if self.health:
            _dict['health'] = self.health.to_dict()
        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if market_type (nullable) is None
        # and model_fields_set contains the field
        if self.market_type is None and "market_type" in self.model_fields_set:
            _dict['market_type'] = None

        # set to None if default_currency (nullable) is None
        # and model_fields_set contains the field
        if self.default_currency is None and "default_currency" in self.model_fields_set:
            _dict['default_currency'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProviderInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "logo": obj.get("logo"),
            "code": obj.get("code"),
            "market_type": obj.get("market_type"),
            "default_currency": obj.get("default_currency"),
            "fees": ProviderFees.from_dict(obj["fees"]) if obj.get("fees") is not None else None,
            "features": ProviderFeatures.from_dict(obj["features"]) if obj.get("features") is not None else None,
            "health": ProviderHealth.from_dict(obj["health"]) if obj.get("health") is not None else None
        })
        return _obj


